package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/Manu343726/cucaracha/pkg/reflect"
)

// FileBuilder helps construct Go source files programmatically
type FileBuilder struct {
	packageName string
	imports     map[string]string // import path -> alias
	code        []string
}

// NewFileBuilder creates a new file builder for a Go package
func NewFileBuilder(packageName string) *FileBuilder {
	return &FileBuilder{
		packageName: packageName,
		imports:     make(map[string]string),
		code:        []string{},
	}
}

// AddImport adds an import to the file
func (fb *FileBuilder) AddImport(path string, alias ...string) *FileBuilder {
	if len(alias) > 0 {
		fb.imports[path] = alias[0]
	} else {
		fb.imports[path] = ""
	}
	return fb
}

// AddCode adds raw Go code to the file
func (fb *FileBuilder) AddCode(code string) *FileBuilder {
	fb.code = append(fb.code, code)
	return fb
}

// AddStruct adds a struct definition from reflect metadata
func (fb *FileBuilder) AddStruct(typ *reflect.Type) (*FileBuilder, error) {
	if typ.Kind != reflect.TypeKindStruct {
		return fb, fmt.Errorf("type is not a struct")
	}

	code := generateStructDef(typ)
	fb.AddCode(code)
	return fb, nil
}

// AddInterface adds an interface definition from reflect metadata
func (fb *FileBuilder) AddInterface(typ *reflect.Type) (*FileBuilder, error) {
	if typ.Kind != reflect.TypeKindInterface {
		return fb, fmt.Errorf("type is not an interface")
	}

	code := generateInterfaceDef(typ)
	fb.AddCode(code)
	return fb, nil
}

// AddEnum adds an enum (type + constants + String method) from reflect metadata
func (fb *FileBuilder) AddEnum(enum *reflect.Enum) *FileBuilder {
	code := generateEnumDef(enum)
	fb.AddCode(code)
	return fb
}

// Build generates the complete Go source file as a string
func (fb *FileBuilder) Build() string {
	var buf bytes.Buffer

	// Write package header
	buf.WriteString("// Code generated by codegen; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n", fb.packageName))

	// Write imports
	if len(fb.imports) > 0 {
		buf.WriteString("\nimport (\n")
		for path, alias := range fb.imports {
			if alias != "" && alias != path {
				buf.WriteString(fmt.Sprintf("\t%s %q\n", alias, path))
			} else {
				buf.WriteString(fmt.Sprintf("\t%q\n", path))
			}
		}
		buf.WriteString(")\n")
	}

	// Write code sections
	if len(fb.code) > 0 {
		buf.WriteString("\n")
		for i, section := range fb.code {
			if i > 0 {
				buf.WriteString("\n")
			}
			buf.WriteString(section)
		}
	}

	return buf.String()
}

// StructBuilder helps construct struct definitions with chainable methods
type StructBuilder struct {
	name   string
	fields []*reflect.Field
	doc    string
}

// NewStructBuilder creates a new struct builder
func NewStructBuilder(name string) *StructBuilder {
	return &StructBuilder{
		name:   name,
		fields: []*reflect.Field{},
	}
}

// WithDoc sets the documentation for the struct
func (sb *StructBuilder) WithDoc(doc string) *StructBuilder {
	sb.doc = doc
	return sb
}

// AddField adds a field to the struct
func (sb *StructBuilder) AddField(fieldName, fieldType string, opts ...string) *StructBuilder {
	field := &reflect.Field{
		Name: fieldName,
		Type: fieldType,
	}

	if len(opts) > 0 {
		field.Doc = opts[0]
	}
	if len(opts) > 1 {
		field.Tag = opts[1]
	}

	sb.fields = append(sb.fields, field)
	return sb
}

// Build constructs the Type from the builder
func (sb *StructBuilder) Build() *reflect.Type {
	return &reflect.Type{
		Name:   sb.name,
		Kind:   reflect.TypeKindStruct,
		Doc:    sb.doc,
		Fields: sb.fields,
	}
}

// InterfaceBuilder helps construct interface definitions
type InterfaceBuilder struct {
	name    string
	methods []*reflect.Method
	doc     string
}

// NewInterfaceBuilder creates a new interface builder
func NewInterfaceBuilder(name string) *InterfaceBuilder {
	return &InterfaceBuilder{
		name:    name,
		methods: []*reflect.Method{},
	}
}

// WithDoc sets the documentation for the interface
func (ib *InterfaceBuilder) WithDoc(doc string) *InterfaceBuilder {
	ib.doc = doc
	return ib
}

// AddMethod adds a method to the interface
func (ib *InterfaceBuilder) AddMethod(methodName string, params []*reflect.Parameter, results []*reflect.Parameter, doc ...string) *InterfaceBuilder {
	method := &reflect.Method{
		Name:    methodName,
		Args:    params,
		Results: results,
	}
	if len(doc) > 0 {
		method.Doc = doc[0]
	}
	ib.methods = append(ib.methods, method)
	return ib
}

// Build constructs the Type from the builder
func (ib *InterfaceBuilder) Build() *reflect.Type {
	return &reflect.Type{
		Name:    ib.name,
		Kind:    reflect.TypeKindInterface,
		Doc:     ib.doc,
		Methods: ib.methods,
	}
}

// EnumBuilder helps construct enum definitions
type EnumBuilder struct {
	name   string
	typ    string // underlying type (int, string, etc)
	values []*reflect.Constant
	doc    string
}

// NewEnumBuilder creates a new enum builder
func NewEnumBuilder(name, underlyingType string) *EnumBuilder {
	return &EnumBuilder{
		name:   name,
		typ:    underlyingType,
		values: []*reflect.Constant{},
	}
}

// WithDoc sets the documentation for the enum
func (eb *EnumBuilder) WithDoc(doc string) *EnumBuilder {
	eb.doc = doc
	return eb
}

// AddValue adds a constant value to the enum
func (eb *EnumBuilder) AddValue(constName string, doc ...string) *EnumBuilder {
	const_ := &reflect.Constant{
		Name: constName,
		Type: eb.name,
	}
	if len(doc) > 0 {
		const_.Doc = doc[0]
	}
	eb.values = append(eb.values, const_)
	return eb
}

// Build constructs the Enum from the builder
func (eb *EnumBuilder) Build() *reflect.Enum {
	return &reflect.Enum{
		Name:         eb.name,
		Type:         eb.typ,
		Doc:          eb.doc,
		Values:       eb.values,
		StringMethod: true,
	}
}

// --- Helper functions for code generation ---

func generateStructDef(typ *reflect.Type) string {
	var buf bytes.Buffer

	// Write documentation
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			buf.WriteString(fmt.Sprintf("// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
		}
	}

	// Write struct declaration
	buf.WriteString(fmt.Sprintf("type %s struct {\n", typ.Name))

	for _, field := range typ.Fields {
		// Write field documentation
		if field.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(field.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		// Write field
		buf.WriteString(fmt.Sprintf("\t%s %s", field.Name, field.Type))
		if field.Tag != "" {
			buf.WriteString(fmt.Sprintf(" `%s`", field.Tag))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateInterfaceDef(typ *reflect.Type) string {
	var buf bytes.Buffer

	// Write documentation
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			buf.WriteString(fmt.Sprintf("// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
		}
	}

	// Write interface declaration
	buf.WriteString(fmt.Sprintf("type %s interface {\n", typ.Name))

	for _, method := range typ.Methods {
		// Write method documentation
		if method.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(method.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		// Write method signature
		argsStr := formatMethodParameters(method.Args)
		resultsStr := formatMethodParameters(method.Results)
		wrapper := ""
		if len(method.Results) > 1 {
			wrapper = "(%s)"
		} else if len(method.Results) == 1 {
			wrapper = "%s"
		}

		if wrapper != "" {
			buf.WriteString(fmt.Sprintf("\t%s(%s) (%s)\n", method.Name, argsStr, resultsStr))
		} else {
			buf.WriteString(fmt.Sprintf("\t%s(%s)\n", method.Name, argsStr))
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateEnumDef(enum *reflect.Enum) string {
	var buf bytes.Buffer

	// Write documentation
	if enum.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(enum.Doc), "\n") {
			buf.WriteString(fmt.Sprintf("// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
		}
	}

	// Write type declaration
	buf.WriteString(fmt.Sprintf("type %s %s\n\n", enum.Name, enum.Type))

	// Write constants
	buf.WriteString("const (\n")
	for i, val := range enum.Values {
		// Write documentation
		if val.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(val.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		if i == 0 {
			buf.WriteString(fmt.Sprintf("\t%s %s = iota\n", val.Name, enum.Name))
		} else {
			buf.WriteString(fmt.Sprintf("\t%s\n", val.Name))
		}
	}
	buf.WriteString(")\n")

	return buf.String()
}

func formatMethodParameters(params []*reflect.Parameter) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		if param.Name != "" {
			parts = append(parts, fmt.Sprintf("%s %s", param.Name, param.Type))
		} else {
			parts = append(parts, param.Type)
		}
	}

	return strings.Join(parts, ", ")
}
