package codegen

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/Manu343726/cucaracha/pkg/reflect"
)

// Generator produces Go source code from reflect.Package metadata
type Generator struct {
	pkg *reflect.Package
}

// NewGenerator creates a new code generator for a parsed package
func NewGenerator(pkg *reflect.Package) *Generator {
	return &Generator{pkg: pkg}
}

// GenerateStructCode generates Go struct definitions
func (g *Generator) GenerateStructCode(typ *reflect.Type) (string, error) {
	if typ.Kind != reflect.TypeKindStruct {
		return "", fmt.Errorf("type %s is not a struct", typ.Name)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by codegen; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("// %s is a generated struct.\n", typ.Name))

	// Write the struct definition
	buf.WriteString(fmt.Sprintf("type %s struct {\n", typ.Name))

	for _, field := range typ.Fields {
		// Write field documentation if available
		if field.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(field.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		// Write field declaration
		buf.WriteString(fmt.Sprintf("\t%s %s", field.Name, field.Type))
		if field.Tag != "" {
			buf.WriteString(fmt.Sprintf(" `%s`", field.Tag))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("}\n")

	return buf.String(), nil
}

// GenerateInterfaceCode generates Go interface definitions
func (g *Generator) GenerateInterfaceCode(typ *reflect.Type) (string, error) {
	if typ.Kind != reflect.TypeKindInterface {
		return "", fmt.Errorf("type %s is not an interface", typ.Name)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by codegen; DO NOT EDIT.\n\n")

	// Write documentation if available
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			buf.WriteString(fmt.Sprintf("// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
		}
	}

	// Write the interface definition
	buf.WriteString(fmt.Sprintf("type %s interface {\n", typ.Name))

	for _, method := range typ.Methods {
		// Write method documentation if available
		if method.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(method.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		// Write method signature
		argsStr := formatParameters(method.Args)
		resultsStr := formatParameters(method.Results)
		buf.WriteString(fmt.Sprintf("\t%s(%s) %s\n", method.Name, argsStr, resultsStr))
	}

	buf.WriteString("}\n")

	return buf.String(), nil
}

// GenerateFunctionSignature generates a function signature that matches reflect.Function
func (g *Generator) GenerateFunctionSignature(fn *reflect.Function) string {
	var buf bytes.Buffer

	receiver := ""
	if fn.IsMethod && fn.Receiver != "" {
		receiver = fmt.Sprintf("(r %s) ", fn.Receiver)
	}

	argsStr := formatParameters(fn.Args)
	resultsStr := formatParameters(fn.Results)

	buf.WriteString(fmt.Sprintf("func %s%s(%s) %s", receiver, fn.Name, argsStr, resultsStr))
	return buf.String()
}

// GenerateEnumCode generates an enum type and String() method
func (g *Generator) GenerateEnumCode(enum *reflect.Enum) string {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by codegen; DO NOT EDIT.\n\n")

	// Write documentation
	if enum.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(enum.Doc), "\n") {
			buf.WriteString(fmt.Sprintf("// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
		}
	}

	// Write type declaration
	buf.WriteString(fmt.Sprintf("type %s %s\n\n", enum.Name, enum.Type))

	// Write constants
	buf.WriteString("const (\n")
	for i, val := range enum.Values {
		if val.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(val.Doc), "\n") {
				buf.WriteString(fmt.Sprintf("\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// ")))
			}
		}

		if i == 0 {
			buf.WriteString(fmt.Sprintf("\t%s %s = iota\n", val.Name, enum.Name))
		} else {
			buf.WriteString(fmt.Sprintf("\t%s\n", val.Name))
		}
	}
	buf.WriteString(")\n")

	// Write String() method if needed
	if enum.StringMethod {
		buf.WriteString(fmt.Sprintf(`
// String returns the string representation of %s
func (e %s) String() string {
	switch e {
`, enum.Name, enum.Name))

		for _, val := range enum.Values {
			// Convert constant name to kebab-case or camelCase
			constName := toCommandName(strings.TrimPrefix(val.Name, enum.Name))
			buf.WriteString(fmt.Sprintf("\tcase %s:\n", val.Name))
			buf.WriteString(fmt.Sprintf("\t\treturn %q\n", constName))
		}

		buf.WriteString(fmt.Sprintf("\tdefault:\n\t\treturn \"unknown\"\n\t}\n}\n"))
	}

	return buf.String()
}

// GenerateBuilderMethod generates a builder-pattern method for initializing a struct
func (g *Generator) GenerateBuilderMethod(typ *reflect.Type) string {
	if typ.Kind != reflect.TypeKindStruct {
		return ""
	}

	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("// New%s creates a new %s instance.\n", typ.Name, typ.Name))
	buf.WriteString(fmt.Sprintf("func New%s() *%s {\n", typ.Name, typ.Name))
	buf.WriteString(fmt.Sprintf("\treturn &%s{}\n", typ.Name))
	buf.WriteString("}\n")

	return buf.String()
}

// formatParameters formats a slice of parameters into a comma-separated list
func formatParameters(params []*reflect.Parameter) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		if param.Name != "" {
			parts = append(parts, fmt.Sprintf("%s %s", param.Name, param.Type))
		} else {
			parts = append(parts, param.Type)
		}
	}

	return strings.Join(parts, ", ")
}

// toCommandName converts a struct/method name to command name (camelCase)
// e.g., "Step" -> "step", "RemoveBreakpoint" -> "removeBreakpoint"
func toCommandName(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[0:1]) + s[1:]
}
