package codegen

import (
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"reflect"
	"slices"
	"strings"
	"text/template"

	cucarachareflex "github.com/Manu343726/cucaracha/pkg/reflect"
	"github.com/Manu343726/cucaracha/pkg/utils"
)

// Generator produces Go source code from cucarachareflex.Package metadata
type Generator struct {
	pkg *cucarachareflex.Package
	w   io.Writer
}

// NewGenerator creates a new code generator for a parsed package
func NewGenerator(pkg *cucarachareflex.Package, w io.Writer) *Generator {
	return &Generator{pkg: pkg, w: w}
}

// GenerateStructCode generates Go struct definitions
func (g *Generator) GenerateStructCode(typ *cucarachareflex.Type) error {
	log().Info("Generating struct code", slog.String("type", typ.Name))

	if typ.Kind != cucarachareflex.TypeKindStruct {
		return log().Errorf("type %s is not a struct", typ.Name)
	}

	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")

	// Write documentation if available, otherwise use default
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
	} else {
		fmt.Fprintf(g.w, "// %s is a generated struct.\n", typ.Name)
	}

	// Write the struct definition
	fmt.Fprintf(g.w, "type %s struct {\n", typ.Name)

	log().Debug("Generating struct fields", slog.String("type", typ.Name), slog.Int("count", len(typ.Fields)))
	for _, field := range typ.Fields {
		log().Debug("Generating field", slog.String("type", typ.Name), slog.String("field", field.Name), slog.String("fieldType", field.Type.Name))

		if field.Name == "" {
			return fmt.Errorf("struct %s has a field with an empty name", typ.Name)
		}

		if field.Type == nil {
			return fmt.Errorf("field %s is missing type information", field.Name)
		}

		// Write field documentation if available
		if field.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(field.Doc), "\n") {
				fmt.Fprintf(g.w, "\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
			}
		}

		// Write field declaration
		fmt.Fprintf(g.w, "\t%s %s", field.Name, field.Type.Name)
		if field.Tag != "" {
			fmt.Fprintf(g.w, " `%s`", field.Tag)
		}
		io.WriteString(g.w, "\n")
	}

	io.WriteString(g.w, "}\n")
	log().Info("Struct code generation complete", slog.String("type", typ.Name))
	return nil
}

// GenerateInterfaceCode generates Go interface definitions
func (g *Generator) GenerateInterfaceCode(typ *cucarachareflex.Type) error {
	log().Info("Generating interface code", slog.String("type", typ.Name))

	if typ.Kind != cucarachareflex.TypeKindInterface {
		return log().Errorf("type %s is not an interface", typ.Name)
	}

	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")

	// Write documentation if available
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
	}

	// Write the interface definition
	fmt.Fprintf(g.w, "type %s interface {\n", typ.Name)

	log().Debug("Generating interface methods", slog.String("type", typ.Name), slog.Int("count", len(typ.Methods)))
	for _, method := range typ.Methods {
		log().Debug("Generating interface method", slog.String("type", typ.Name), slog.String("method", method.Name))

		// Write method documentation if available
		if method.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(method.Doc), "\n") {
				fmt.Fprintf(g.w, "\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
			}
		}

		// Write method signature
		argsStr := formatParameters(method.Args)
		resultsStr := formatParametersWithParens(method.Results)
		fmt.Fprintf(g.w, "\t%s(%s) %s\n", method.Name, argsStr, resultsStr)
	}

	io.WriteString(g.w, "}\n")
	log().Info("Interface code generation complete", slog.String("type", typ.Name))
	return nil
}

// GenerateMethodSignature generates a method signature that matches cucarachareflex.Method
func (g *Generator) GenerateMethodSignature(fn *cucarachareflex.Method) {
	argsStr := formatParameters(fn.Args)
	resultsStr := formatParametersWithParens(fn.Results)

	if resultsStr != "" {
		fmt.Fprintf(g.w, "func (%s %s) %s(%s) %s", fn.Receiver.Name, fn.Receiver.Type.Name, fn.Name, argsStr, resultsStr)
	} else {
		fmt.Fprintf(g.w, "func (%s %s) %s(%s)", fn.Receiver.Name, fn.Receiver.Type.Name, fn.Name, argsStr)
	}
}

// GenerateFunctionSignature generates a function signature that matches cucarachareflex.Function
func (g *Generator) GenerateFunctionSignature(fn *cucarachareflex.Function) {
	argsStr := formatParameters(fn.Args)
	resultsStr := formatParametersWithParens(fn.Results)

	if resultsStr != "" {
		fmt.Fprintf(g.w, "func %s(%s) %s", fn.Name, argsStr, resultsStr)
	} else {
		fmt.Fprintf(g.w, "func %s(%s)", fn.Name, argsStr)
	}
}

// FunctionImplementation contains all parameters needed to generate a function implementation.
// It specifies the function signature, the template for the function body, and context data
// for template rendering.
type FunctionImplementation struct {
	// Function is the cucarachareflex.Function describing the function signature.
	Function *cucarachareflex.Function `json:"function"`

	// BodyTemplate is a text/template string for rendering the function body.
	// The template receives TemplateContext as its data.
	BodyTemplate string `json:"bodyTemplate"`

	// TemplateContext is arbitrary data passed to the template.
	// It can contain values, functions, or any data needed during template rendering.
	TemplateContext interface{} `json:"templateContext"`
}

// MethodImplementation contains all parameters needed to generate a method implementation.
// It specifies the method signature, the template for the method body, and context data
// for template rendering.
type MethodImplementation struct {
	// Method is the cucarachareflex.Method describing the method signature and receiver.
	Method *cucarachareflex.Method `json:"method"`

	// BodyTemplate is a text/template string for rendering the method body.
	// The template receives TemplateContext as its data.
	BodyTemplate string `json:"bodyTemplate"`

	// TemplateContext is arbitrary data passed to the template.
	// It can contain values, functions, or any data needed during template rendering.
	TemplateContext interface{} `json:"templateContext"`
}

// GenerateFunctionImplementation generates a complete function implementation with a body based on a template
func (g *Generator) GenerateFunctionImplementation(fn *FunctionImplementation) error {
	return g.GenerateFunctionImplementationWithOpts(fn, FunctionGenerationOpts{})
}

// GenerateMethodImplementation generates a complete method implementation with a body based on a template
func (g *Generator) GenerateMethodImplementation(methodImpl *MethodImplementation) error {
	return g.GenerateMethodImplementationWithOpts(methodImpl, FunctionGenerationOpts{})
}

// FunctionGenerationOpts provides optional configuration for function generation
type FunctionGenerationOpts struct {
	// TemplateFuncs is a map of custom template functions to make available in the template
	TemplateFuncs template.FuncMap

	// WriteDocs controls whether to write the function documentation comment
	WriteDocs bool

	// IndentLevel specifies the indentation level for the generated code
	IndentLevel int
}

// GenerateFunctionImplementationWithOpts generates a complete function implementation
// with customizable options for template functions, documentation, and formatting.
//
// Parameters:
//   - fn: the reflect.Function instance describing the function's signature
//   - templateBody: a text/template template string for the function body
//   - context: context data passed to the template for rendering the body
//   - opts: FunctionGenerationOpts to customize the generation behavior
//
// Returns an error if:
//   - The template is invalid
//   - Template execution fails
//   - Writing to the output fails
func (g *Generator) GenerateFunctionImplementationWithOpts(fn *FunctionImplementation, opts FunctionGenerationOpts) error {
	// We trick the code generator into treating this as a method implementation by creating a dummy MethodImplementation
	// This allows us to reuse the same code generation logic for both functions and methods, since the main difference is just whether there is a receiver or not.
	return g.GenerateMethodImplementationWithOpts(&MethodImplementation{
		Method: &cucarachareflex.Method{
			Name:    fn.Function.Name,
			Args:    fn.Function.Args,
			Results: fn.Function.Results,
			Doc:     fn.Function.Doc,
		},
		BodyTemplate:    fn.BodyTemplate,
		TemplateContext: fn.TemplateContext,
	}, opts)
}

// GenerateMethodImplementationWithOpts generates a complete method implementation with customizable options
// See [GenerateFunctionImplementationWithOpts] for details on parameters and behavior
func (g *Generator) GenerateMethodImplementationWithOpts(f *MethodImplementation, opts FunctionGenerationOpts) error {
	indentStr := strings.Repeat("\t", opts.IndentLevel)
	// Write documentation if requested and available
	if opts.WriteDocs && f.Method.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(f.Method.Doc), "\n") {
			cleanedLine := strings.TrimPrefix(strings.TrimSpace(line), "//")
			fmt.Fprintf(g.w, "%s// %s\n", indentStr, strings.TrimSpace(cleanedLine))
		}
	}

	// Write function signature
	fmt.Fprintf(g.w, "%s", indentStr)
	if f.Method.Receiver != nil {
		g.GenerateMethodSignature(f.Method)
	} else {
		g.GenerateFunctionSignature(&cucarachareflex.Function{
			Name:    f.Method.Name,
			Args:    f.Method.Args,
			Results: f.Method.Results,
			Doc:     f.Method.Doc,
		})
	}
	io.WriteString(g.w, " {\n")

	// Parse and execute the template for the function body
	tmpl, err := template.New(f.Method.Name).Funcs(opts.TemplateFuncs).Parse(f.BodyTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse function body template for %s: %w", f.Method.Name, err)
	}

	// Create a buffered writer to capture template output
	bodyIndentStr := strings.Repeat("\t", opts.IndentLevel+1)

	// Execute template and write each line with proper indentation
	var bodyBuf strings.Builder
	if err := tmpl.Execute(&bodyBuf, f.TemplateContext); err != nil {
		return fmt.Errorf("failed to execute function body template for %s: %w", f.Method.Name, err)
	}

	// Write the body with proper indentation
	bodyContent := bodyBuf.String()
	for _, line := range strings.Split(strings.TrimSuffix(bodyContent, "\n"), "\n") {
		if line != "" {
			fmt.Fprintf(g.w, "%s%s\n", bodyIndentStr, line)
		} else {
			io.WriteString(g.w, "\n")
		}
	}

	// Write closing brace
	fmt.Fprintf(g.w, "%s}\n", indentStr)

	return nil
}

// GenerateEnumCode generates an enum type and String() method
func (g *Generator) GenerateEnumCode(enum *cucarachareflex.Enum) error {
	log().Info("Generating enum code", slog.String("enum", enum.Type.Name), slog.String("typeKind", string(enum.Type.Type.Kind)))

	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")

	// Generate the appropriate type definition based on whether it's an alias or typedef
	switch enum.Type.Type.Kind {
	case cucarachareflex.TypeKindAlias:
		if err := g.generateAliasCodeWithoutHeader(enum.Type.Type); err != nil {
			return fmt.Errorf("failed to generate type alias for enum %s: %w", enum.Type.Name, err)
		}
	case cucarachareflex.TypeKindTypedef:
		if err := g.generateTypedefCodeWithoutHeader(enum.Type.Type); err != nil {
			return fmt.Errorf("failed to generate type typedef for enum %s: %w", enum.Type.Name, err)
		}
	default:
		return log().Errorf("enum type %s must be either an alias or typedef, got %s", enum.Type.Name, enum.Type.Type.Kind)
	}

	// Write blank line before const block
	io.WriteString(g.w, "\n")

	// Write constants
	io.WriteString(g.w, "const (\n")
	for i, val := range enum.Values {
		if val.Doc != "" {
			for _, line := range strings.Split(strings.TrimSpace(val.Doc), "\n") {
				fmt.Fprintf(g.w, "\t// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
			}
		}

		// Make sure the constant has the same type as the enum
		if val.Value.Type == nil {
			val.Value.Type = enum.Type
		}

		// generate literal code for the constant value after the equals sign
		fmt.Fprintf(g.w, "\t%s", val.Name)

		// Only write the type and value if a value is provided
		if val.Value.Value != nil {
			fmt.Fprintf(g.w, " %s = ", enum.Type.Name)

			// For enum constants with string values like "iota", write them directly
			if strVal, ok := val.Value.Value.(string); ok {
				io.WriteString(g.w, strVal)
			} else if err := g.GenerateValue(val.Value); err != nil {
				return fmt.Errorf("failed to generate value for enum constant[%d] '%s': %w", i, val.Name, err)
			}
		}

		io.WriteString(g.w, "\n")
	}
	io.WriteString(g.w, ")\n")

	// Write String() method if needed
	if enum.StringMethod {
		fmt.Fprintf(g.w, "\n// String returns the string representation of %s\n", enum.Type.Name)
		fmt.Fprintf(g.w, "func (e %s) String() string {\n", enum.Type.Name)
		io.WriteString(g.w, "\tswitch e {\n")

		for _, val := range enum.Values {
			// Convert constant name to kebab-case or camelCase
			constName := toCommandName(strings.TrimPrefix(val.Name, enum.Type.Name))
			fmt.Fprintf(g.w, "\tcase %s:\n", val.Name)
			fmt.Fprintf(g.w, "\t\treturn %q\n", constName)
		}

		io.WriteString(g.w, "\tdefault:\n\t\treturn \"unknown\"\n\t}\n}\n")
	}

	// Generate additional enum support methods (always generated; not optional)
	// These include string conversion functions used by command dispatching
	if err := g.generateEnumToStringMethod(enum); err != nil {
		return fmt.Errorf("failed to generate String() method for enum %s: %w", enum.Type.Name, err)
	}

	if err := g.generateEnumFromStringFunction(enum); err != nil {
		return fmt.Errorf("failed to generate FromString function for enum %s: %w", enum.Type.Name, err)
	}

	if err := g.generateEnumMarshalJSONMethod(enum); err != nil {
		return fmt.Errorf("failed to generate MarshalJSON method for enum %s: %w", enum.Type.Name, err)
	}

	if err := g.generateEnumUnmarshalJSONMethod(enum); err != nil {
		return fmt.Errorf("failed to generate UnmarshalJSON method for enum %s: %w", enum.Type.Name, err)
	}

	if err := g.generateEnumValuesMap(enum); err != nil {
		return fmt.Errorf("failed to generate values map for enum %s: %w", enum.Type.Name, err)
	}

	return nil
}

func (g *Generator) generateEnumToStringMethod(enum *cucarachareflex.Enum) error {
	return g.GenerateMethodImplementation(&MethodImplementation{
		Method: &cucarachareflex.Method{
			Name: "String",
			Results: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: "string"},
				},
			},
			Receiver: &cucarachareflex.Parameter{
				Name: "e",
				Type: &cucarachareflex.TypeReference{Name: enum.Type.Name},
			},
		},
		BodyTemplate: `
switch e {
{{- range .Values }}
case {{.Name}}:
	return "{{call $.stringValue .Name}}"
{{- end }}
default:
	return "unknown"
}
`,
		TemplateContext: map[string]interface{}{
			"Values": enum.Values,
			"Name":   enum.Type.Name,
			"stringValue": func(name string) string {
				return strings.TrimPrefix(name, enum.Type.Name)
			},
		},
	})
}

func (g *Generator) generateEnumFromStringFunction(enum *cucarachareflex.Enum) error {
	return g.GenerateFunctionImplementation(&FunctionImplementation{
		Function: &cucarachareflex.Function{
			Name: enum.Type.Name + "FromString",
			Args: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Name: "s",
					Type: &cucarachareflex.TypeReference{Name: "string"},
				},
			},
			Results: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: enum.Type.Name},
				},
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: "error"},
				},
			},
		},
		BodyTemplate: `
switch s {
{{- range .Values }}
case "{{call $.stringValue .Name}}":
	return {{.Name}}, nil
{{- end }}
default:
	return 0, fmt.Errorf("unknown %s: %s", "{{.Name}}", s)
}
`,
		TemplateContext: map[string]interface{}{
			"Values": enum.Values,
			"Name":   enum.Type.Name,
			"stringValue": func(name string) string {
				return strings.TrimPrefix(name, enum.Type.Name)
			},
		},
	})
}

func (g *Generator) generateEnumMarshalJSONMethod(enum *cucarachareflex.Enum) error {
	return g.GenerateMethodImplementation(&MethodImplementation{
		Method: &cucarachareflex.Method{
			Name: "MarshalJSON",
			Receiver: &cucarachareflex.Parameter{
				Name: "e",
				Type: &cucarachareflex.TypeReference{Name: enum.Type.Name},
			},
			Results: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: "[]byte"},
				},
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: "error"},
				},
			},
		},
		BodyTemplate: `
return json.Marshal(e.String())`,
	})
}

func (g *Generator) generateEnumUnmarshalJSONMethod(enum *cucarachareflex.Enum) error {
	return g.GenerateMethodImplementation(&MethodImplementation{
		Method: &cucarachareflex.Method{
			Name: "UnmarshalJSON",
			Receiver: &cucarachareflex.Parameter{
				Name: "e",
				Type: &cucarachareflex.TypeReference{Name: "*" + enum.Type.Name},
			},
			Args: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Name: "data",
					Type: &cucarachareflex.TypeReference{Name: "[]byte"},
				},
			},
			Results: []*cucarachareflex.Parameter{
				&cucarachareflex.Parameter{
					Type: &cucarachareflex.TypeReference{Name: "error"},
				},
			},
		},
		BodyTemplate: `
var str string
if err := json.Unmarshal(data, &str); err != nil {
	return err
}
val, err := {{.Name}}FromString(str)
if err != nil {
	return err
}
*e = val

return nil`,
		TemplateContext: map[string]interface{}{
			"Name": enum.Type.Name,
		},
	})
}

func (g *Generator) generateEnumValuesMap(enum *cucarachareflex.Enum) error {
	return g.GenerateVariable(&cucarachareflex.Variable{
		Doc:  fmt.Sprintf("A map of all %s values for easy lookup", enum.Type.Name),
		Name: enum.Type.Name + "Values",
		Value: &cucarachareflex.Value{
			Type: cucarachareflex.MakeTypeReference(cucarachareflex.Map(
				cucarachareflex.Typedef(enum.Type.Name, cucarachareflex.TypeInt),
				cucarachareflex.TypeBool)),
			Value: utils.GenMapFromKeys(
				utils.Map(enum.Values, func(val *cucarachareflex.Constant) *cucarachareflex.Value {
					return val.Value
				}),
				func(c *cucarachareflex.Value) *cucarachareflex.Value {
					return cucarachareflex.NewValue(true)
				}),
		},
	})
}

// GenerateBuilderMethod generates a builder-pattern method for initializing a struct
func (g *Generator) GenerateBuilderMethod(typ *cucarachareflex.Type) error {
	if typ.Kind != cucarachareflex.TypeKindStruct {
		return fmt.Errorf("type %s is not a struct", typ.Name)
	}

	fmt.Fprintf(g.w, "// New%s creates a new %s instance.\n", typ.Name, typ.Name)
	fmt.Fprintf(g.w, "func New%s() *%s {\n", typ.Name, typ.Name)
	fmt.Fprintf(g.w, "\treturn &%s{}\n", typ.Name)
	io.WriteString(g.w, "}\n")

	return nil
}

func (g *Generator) GenerateVariable(variable *cucarachareflex.Variable) error {
	// Write documentation if available
	if variable.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(variable.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
	}

	fmt.Fprintf(g.w, "var %s %s = ", variable.Name, variable.Value.Type.Name)
	return g.GenerateValue(variable.Value)
}

// generateAliasCodeWithoutHeader generates the type alias definition without the header
func (g *Generator) generateAliasCodeWithoutHeader(typ *cucarachareflex.Type) error {
	if typ.Kind != cucarachareflex.TypeKindAlias {
		return fmt.Errorf("type %s is not an alias", typ.Name)
	}

	// Write documentation if available
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
	}

	// Get the underlying type name
	underlyingType := typ.Name // Default fallback
	if typ.OriginalType != nil {
		underlyingType = typ.OriginalType.Name
	} else if typ.Elem != nil {
		underlyingType = typ.Elem.Name
	}

	// Write the alias definition
	fmt.Fprintf(g.w, "type %s = %s\n", typ.Name, underlyingType)

	return nil
}

// GenerateAliasCode generates a Go type alias definition
// For example: type MyInt = int
func (g *Generator) GenerateAliasCode(typ *cucarachareflex.Type) error {
	if typ.Kind != cucarachareflex.TypeKindAlias {
		return fmt.Errorf("type %s is not an alias", typ.Name)
	}

	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")
	return g.generateAliasCodeWithoutHeader(typ)
}

// generateTypedefCodeWithoutHeader generates the type typedef definition without the header
func (g *Generator) generateTypedefCodeWithoutHeader(typ *cucarachareflex.Type) error {
	if typ.Kind != cucarachareflex.TypeKindTypedef {
		log().Error("Type is not a typedef", slog.String("type", typ.Name), slog.String("kind", string(typ.Kind)))
		return log().Errorf("type %s is not a typedef", typ.Name)
	}

	// Write documentation if available
	if typ.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(typ.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
	}

	// Get the underlying type name
	underlyingType := typ.Name // Default fallback
	if typ.OriginalType != nil {
		underlyingType = typ.OriginalType.Name
	} else if typ.Elem != nil {
		underlyingType = typ.Elem.Name
	}

	log().Debug("Generating typedef", slog.String("name", typ.Name), slog.String("underlying", underlyingType))

	// Write the typedef definition (without =)
	fmt.Fprintf(g.w, "type %s %s\n", typ.Name, underlyingType)
	return nil
}

// GenerateTypedefCode generates a Go type definition (typedef)
// For example: type MyInt int
func (g *Generator) GenerateTypedefCode(typ *cucarachareflex.Type) error {
	log().Info("Generating typedef code", slog.String("type", typ.Name))

	if typ.Kind != cucarachareflex.TypeKindTypedef {
		log().Error("Type is not a typedef", slog.String("type", typ.Name), slog.String("kind", string(typ.Kind)))
		return log().Errorf("type %s is not a typedef", typ.Name)
	}

	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")
	return g.generateTypedefCodeWithoutHeader(typ)
}

// Generates a Go literal for a given cucarachareflex.Value, using cucaracha reflect Type for type information.
func (g *Generator) GenerateValue(value *cucarachareflex.Value) error {
	return g.generateValueInternal(value, 0)
}

func (g *Generator) generateValueInternal(value *cucarachareflex.Value, indent int) error {
	if value.Type == nil {
		log().Panic("Value is missing type information", slog.Any("value", value))
	}

	switch value.Type.Type {
	// For basic types, we assume the value is given in the equivalent Go type and so we can format it directly as a literal:
	case cucarachareflex.TypeBool:
		if b, ok := value.Value.(bool); ok {
			fmt.Fprintf(g.w, "%v", b)
			return nil
		} else {
			return fmt.Errorf("expected bool value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeByte:
		if b, ok := value.Value.(byte); ok {
			fmt.Fprintf(g.w, "%d", b)
			return nil
		} else {
			return fmt.Errorf("expected byte value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeRune:
		if r, ok := value.Value.(rune); ok {
			fmt.Fprintf(g.w, "%d", r)
			return nil
		} else {
			return fmt.Errorf("expected rune value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeInt:
		if i, ok := value.Value.(int); ok {
			fmt.Fprintf(g.w, "%d", i)
			return nil
		} else {
			return fmt.Errorf("expected int value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeInt8:
		if i, ok := value.Value.(int8); ok {
			fmt.Fprintf(g.w, "%d", i)
			return nil
		} else {
			return fmt.Errorf("expected int8 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeInt16:
		if i, ok := value.Value.(int16); ok {
			fmt.Fprintf(g.w, "%d", i)
			return nil
		} else {
			return fmt.Errorf("expected int16 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeInt32:
		if i, ok := value.Value.(int32); ok {
			fmt.Fprintf(g.w, "%d", i)
			return nil
		} else {
			return fmt.Errorf("expected int32 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeInt64:
		if i, ok := value.Value.(int64); ok {
			fmt.Fprintf(g.w, "%d", i)
			return nil
		} else {
			return fmt.Errorf("expected int64 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUint:
		if u, ok := value.Value.(uint); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uint value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUint8:
		if u, ok := value.Value.(uint8); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uint8 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUint16:
		if u, ok := value.Value.(uint16); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uint16 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUint32:
		if u, ok := value.Value.(uint32); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uint32 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUint64:
		if u, ok := value.Value.(uint64); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uint64 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeUintptr:
		if u, ok := value.Value.(uintptr); ok {
			fmt.Fprintf(g.w, "%d", u)
			return nil
		} else {
			return fmt.Errorf("expected uintptr value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeFloat32:
		if f, ok := value.Value.(float32); ok {
			fmt.Fprintf(g.w, "%v", f)
			return nil
		} else {
			return fmt.Errorf("expected float32 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeFloat64:
		if f, ok := value.Value.(float64); ok {
			fmt.Fprintf(g.w, "%v", f)
			return nil
		} else {
			return fmt.Errorf("expected float64 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeComplex64:
		if c, ok := value.Value.(complex64); ok {
			fmt.Fprintf(g.w, "%v", c)
			return nil
		} else {
			return fmt.Errorf("expected complex64 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeComplex128:
		if c, ok := value.Value.(complex128); ok {
			fmt.Fprintf(g.w, "%v", c)
			return nil
		} else {
			return fmt.Errorf("expected complex128 value for type %s, got %T", value.Type.Name, value.Value)
		}
	case cucarachareflex.TypeString:
		if str, ok := value.Value.(string); ok {
			fmt.Fprintf(g.w, "%q", str)
			return nil
		} else {
			return fmt.Errorf("expected string value for type %s, got %T", value.Type.Name, value.Value)
		}
	default:
		if value.Type.Type.IsBasic() {
			panic(fmt.Sprintf("basic types should have been handled in the switch statement, but got unhandled basic type: %s", value.Type.Type.Kind.String()))
		}

		// For non-basic types, we recursively walk across the type system trying to resolve the value:
		switch value.Type.Type.Kind {
		case cucarachareflex.TypeKindStruct:
			return g.generateStructValue(value, indent)
		case cucarachareflex.TypeKindSlice:
			return g.generateSliceValue(value, indent)
		case cucarachareflex.TypeKindArray:
			return g.generateArrayValue(value, indent)
		case cucarachareflex.TypeKindMap:
			return g.generateMapValue(value, indent)
		case cucarachareflex.TypeKindPointer:
			return g.generatePointerValue(value, indent)
		case cucarachareflex.TypeKindInterface:
			return g.generateInterfaceValue(value, indent)
		case cucarachareflex.TypeKindAlias, cucarachareflex.TypeKindTypedef:
			return g.generateAliasValue(value, indent)
		default:
			return fmt.Errorf("unsupported type kind: %s", value.Type.Type.Kind.String())
		}
	}
}

func (g *Generator) generateStructValue(value *cucarachareflex.Value, indent int) error {
	// We expect the value to be a map of field names to values
	fields, ok := value.Value.(map[string]*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected struct value to be a map of field names to values, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "%s{\n", value.Type.Type.Name)

	nextIndent := indent + 1
	indentStr := strings.Repeat("\t", nextIndent)

	for _, field := range value.Type.Type.Fields {
		fieldValue, exists := fields[field.Name]
		if !exists {
			return fmt.Errorf("missing value for struct field %s", field.Name)
		}

		fmt.Fprintf(g.w, "%s%s: ", indentStr, field.Name)
		err := g.generateValueInternal(fieldValue, nextIndent)
		if err != nil {
			return fmt.Errorf("failed to generate value for struct field %s: %w", field.Name, err)
		}
		io.WriteString(g.w, ",\n")
	}

	fmt.Fprintf(g.w, "%s}", strings.Repeat("\t", indent))
	return nil
}

func (g *Generator) generateSliceValue(value *cucarachareflex.Value, indent int) error {
	// We expect the value to be a slice of values
	values, ok := value.Value.([]*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected slice value to be a slice of values, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "[]%s{\n", value.Type.Type.Elem.Name)

	nextIndent := indent + 1
	indentStr := strings.Repeat("\t", nextIndent)

	for _, elemValue := range values {
		fmt.Fprintf(g.w, "%s", indentStr)
		err := g.generateValueInternal(elemValue, nextIndent)
		if err != nil {
			return fmt.Errorf("failed to generate value for slice element: %w", err)
		}
		io.WriteString(g.w, ",\n")
	}

	fmt.Fprintf(g.w, "%s}", strings.Repeat("\t", indent))
	return nil
}

func (g *Generator) generateArrayValue(value *cucarachareflex.Value, indent int) error {
	// We expect the value to be a slice of values
	values, ok := value.Value.([]*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected array value to be a slice of values, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "[%d]%s{\n", len(values), value.Type.Type.Elem.Name)

	nextIndent := indent + 1
	indentStr := strings.Repeat("\t", nextIndent)

	for _, elemValue := range values {
		fmt.Fprintf(g.w, "%s", indentStr)
		err := g.generateValueInternal(elemValue, nextIndent)
		if err != nil {
			return fmt.Errorf("failed to generate value for array element: %w", err)
		}
		io.WriteString(g.w, ",\n")
	}

	fmt.Fprintf(g.w, "%s}", strings.Repeat("\t", indent))
	return nil
}

func (g *Generator) generateMapValue(value *cucarachareflex.Value, indent int) error {
	// We expect the value to be a map of keys to values
	mapValues, ok := value.Value.(map[*cucarachareflex.Value]*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected map value to be a map of keys to values, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "map[%s]%s{\n", value.Type.Type.Key.Name, value.Type.Type.Value.Name)

	nextIndent := indent + 1
	indentStr := strings.Repeat("\t", nextIndent)

	// Sort the keys for deterministic output
	keys := make([]*cucarachareflex.Value, 0, len(mapValues))
	for key := range mapValues {
		keys = append(keys, key)
	}
	slices.SortFunc(keys, func(a, b *cucarachareflex.Value) int {
		return a.Compare(b)
	})

	// Check if the key type is an enum - if so, we'll use constant names instead of raw values
	keyTypeName := value.Type.Type.Key.Name
	var enumDef *cucarachareflex.Enum
	if g.pkg != nil && g.pkg.Enums != nil {
		enumDef = g.pkg.Enums[keyTypeName]
	}

	// Iterate over sorted keys
	for _, key := range keys {
		val := mapValues[key]
		fmt.Fprintf(g.w, "%s", indentStr)

		// If the key type is an enum, look up the constant name
		if enumDef != nil {
			constantName := ""
			for _, constant := range enumDef.Values {
				if constant.Value.Compare(key) == 0 {
					constantName = constant.Name
					break
				}
			}
			if constantName != "" {
				io.WriteString(g.w, constantName)
			} else {
				// Fallback to raw value if constant not found
				err := g.generateValueInternal(key, nextIndent)
				if err != nil {
					return fmt.Errorf("failed to generate value for map key: %w", err)
				}
			}
		} else {
			err := g.generateValueInternal(key, nextIndent)
			if err != nil {
				return fmt.Errorf("failed to generate value for map key: %w", err)
			}
		}

		io.WriteString(g.w, ": ")
		err := g.generateValueInternal(val, nextIndent)
		if err != nil {
			return fmt.Errorf("failed to generate value for map value: %w", err)
		}
		io.WriteString(g.w, ",\n")
	}

	fmt.Fprintf(g.w, "%s}", strings.Repeat("\t", indent))
	return nil
}

func (g *Generator) generatePointerValue(value *cucarachareflex.Value, indent int) error {
	// We expect the value to be a pointer to another value
	elemValue, ok := value.Value.(*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected pointer value to be a pointer to another value, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "&")
	return g.generateValueInternal(elemValue, indent)
}

func (g *Generator) generateInterfaceValue(value *cucarachareflex.Value, indent int) error {
	// For interface values, we just generate the underlying value
	underlyingValue, ok := value.Value.(*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected interface value to be a pointer to another value, got %T", value.Value)
	}

	return g.generateValueInternal(underlyingValue, indent)
}

func (g *Generator) generateAliasValue(value *cucarachareflex.Value, indent int) error {
	// For alias values, we just generate the underlying value with a type cast to the alias type
	underlyingValue, ok := value.Value.(*cucarachareflex.Value)
	if !ok {
		return fmt.Errorf("expected alias value to be a pointer to another value, got %T", value.Value)
	}

	fmt.Fprintf(g.w, "%s(", value.Type.Name)
	err := g.generateValueInternal(underlyingValue, indent)
	if err != nil {
		return fmt.Errorf("failed to generate value for alias: %w", err)
	}
	io.WriteString(g.w, ")")

	return nil
}

// Generates a Go literal for a given value using golang runtime reflection for type information.
// The indent parameter controls the indentation level for nested structures.
func (g *Generator) GenerateGoValue(value interface{}) error {
	return g.generateGoValueInternal(value, 0)
}

func (g *Generator) generateGoValueInternal(value interface{}, indent int) error {
	rVal := reflect.ValueOf(value)

	// Handle nil values - check IsValid() FIRST before calling Type()
	if !rVal.IsValid() {
		io.WriteString(g.w, "nil")
		return nil
	}

	rType := rVal.Type()

	// Handle pointer dereferencing
	if rType.Kind() == reflect.Ptr {
		if rVal.IsNil() {
			io.WriteString(g.w, "nil")
			return nil
		}
		return g.generateGoValueInternal(rVal.Elem().Interface(), indent)
	}

	// Handle basic types
	switch rType.Kind() {
	case reflect.String:
		fmt.Fprintf(g.w, "%q", rVal.String())
		return nil

	case reflect.Bool:
		fmt.Fprintf(g.w, "%v", rVal.Bool())
		return nil

	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fmt.Fprintf(g.w, "%d", rVal.Int())
		return nil

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		fmt.Fprintf(g.w, "%d", rVal.Uint())
		return nil

	case reflect.Float32, reflect.Float64:
		fmt.Fprintf(g.w, "%v", rVal.Float())
		return nil

	case reflect.Complex64, reflect.Complex128:
		fmt.Fprintf(g.w, "%v", rVal.Complex())
		return nil

	case reflect.Array:
		return g.generateArrayGoValue(rVal, rType, indent)

	case reflect.Slice:
		return g.generateSliceGoValue(rVal, rType, indent)

	case reflect.Map:
		return g.generateMapGoValue(rVal, rType, indent)

	case reflect.Struct:
		return g.generateStructGoValue(rVal, rType, indent)

	case reflect.Interface:
		// For interface types, generate the underlying value
		if rVal.IsNil() {
			io.WriteString(g.w, "nil")
			return nil
		}
		return g.generateGoValueInternal(rVal.Interface(), indent)

	default:
		return fmt.Errorf("unsupported type: %s", rType.String())
	}
}

// generateArrayGoValue generates a formatted array literal
func (g *Generator) generateArrayGoValue(rVal reflect.Value, rType reflect.Type, indent int) error {
	elemType := rType.Elem()

	// Array type with length
	fmt.Fprintf(g.w, "[%d]%s{", rVal.Len(), elemType.String())

	if rVal.Len() > 0 {
		io.WriteString(g.w, "\n")
		nextIndent := indent + 1
		indentStr := strings.Repeat("\t", nextIndent)

		for i := 0; i < rVal.Len(); i++ {
			io.WriteString(g.w, indentStr)
			err := g.generateGoValueInternal(rVal.Index(i).Interface(), nextIndent)
			if err != nil {
				return err
			}
			if i < rVal.Len()-1 {
				io.WriteString(g.w, ",")
			}
			io.WriteString(g.w, "\n")
		}

		io.WriteString(g.w, strings.Repeat("\t", indent))
	}

	io.WriteString(g.w, "}")
	return nil
}

// generateSliceGoValue generates a formatted slice literal
func (g *Generator) generateSliceGoValue(rVal reflect.Value, rType reflect.Type, indent int) error {
	elemType := rType.Elem()

	// Slice type
	fmt.Fprintf(g.w, "[]%s{", elemType.String())

	if rVal.Len() > 0 {
		io.WriteString(g.w, "\n")
		nextIndent := indent + 1
		indentStr := strings.Repeat("\t", nextIndent)

		for i := 0; i < rVal.Len(); i++ {
			io.WriteString(g.w, indentStr)
			err := g.generateGoValueInternal(rVal.Index(i).Interface(), nextIndent)
			if err != nil {
				return err
			}
			if i < rVal.Len()-1 {
				io.WriteString(g.w, ",")
			}
			io.WriteString(g.w, "\n")
		}

		io.WriteString(g.w, strings.Repeat("\t", indent))
	}

	io.WriteString(g.w, "}")
	return nil
}

// generateMapGoValue generates a formatted map literal
func (g *Generator) generateMapGoValue(rVal reflect.Value, rType reflect.Type, indent int) error {
	keyType := rType.Key()
	valType := rType.Elem()

	// Map type
	fmt.Fprintf(g.w, "map[%s]%s{", keyType.String(), valType.String())

	if rVal.Len() > 0 {
		io.WriteString(g.w, "\n")
		nextIndent := indent + 1
		indentStr := strings.Repeat("\t", nextIndent)

		// Get keys for iteration and sort them for deterministic output
		keys := rVal.MapKeys()
		slices.SortFunc(keys, func(a, b reflect.Value) int {
			// Create Value objects from the reflect values for comparison
			aVal := &cucarachareflex.Value{Value: a.Interface()}
			bVal := &cucarachareflex.Value{Value: b.Interface()}
			return aVal.Compare(bVal)
		})

		for i, key := range keys {
			io.WriteString(g.w, indentStr)
			err := g.generateGoValueInternal(key.Interface(), nextIndent)
			if err != nil {
				return err
			}

			io.WriteString(g.w, ": ")

			val := rVal.MapIndex(key)
			err = g.generateGoValueInternal(val.Interface(), nextIndent)
			if err != nil {
				return err
			}

			if i < len(keys)-1 {
				io.WriteString(g.w, ",")
			}
			io.WriteString(g.w, "\n")
		}

		io.WriteString(g.w, strings.Repeat("\t", indent))
	}

	io.WriteString(g.w, "}")
	return nil
}

// generateStructGoValue generates a formatted struct literal
func (g *Generator) generateStructGoValue(rVal reflect.Value, rType reflect.Type, indent int) error {
	typeName := rType.Name()
	if typeName == "" {
		// Anonymous struct
		typeName = rType.String()
	}

	io.WriteString(g.w, typeName)
	io.WriteString(g.w, "{")

	numFields := rVal.NumField()
	if numFields > 0 {
		io.WriteString(g.w, "\n")
		nextIndent := indent + 1
		indentStr := strings.Repeat("\t", nextIndent)

		for i := 0; i < numFields; i++ {
			field := rType.Field(i)
			fieldVal := rVal.Field(i)

			// Skip unexported fields
			if len(field.Name) == 0 || field.Name[0] >= 'a' && field.Name[0] <= 'z' {
				continue
			}

			io.WriteString(g.w, indentStr)
			io.WriteString(g.w, field.Name)
			io.WriteString(g.w, ": ")

			err := g.generateGoValueInternal(fieldVal.Interface(), nextIndent)
			if err != nil {
				return err
			}

			if i < numFields-1 {
				io.WriteString(g.w, ",")
			}
			io.WriteString(g.w, "\n")
		}

		io.WriteString(g.w, strings.Repeat("\t", indent))
	}

	io.WriteString(g.w, "}")
	return nil
}

// Generate generates code for multiple cucaracha/reflect values in the order provided.
// It handles Function, Type (struct/interface/alias), and Enum types, calling the appropriate
// generation method for each value. Values are separated by blank lines in the output.
//
// Supported types:
//   - *cucarachareflex.Function: generates function signature
//   - *cucarachareflex.Type: generates struct, interface, or alias code based on Kind
//   - *cucarachareflex.Enum: generates enum type and String() method
//
// Returns an error if:
//   - An unsupported type is provided
//   - Code generation for a specific value fails
//   - Writing to the output fails
func (g *Generator) Generate(values ...interface{}) error {
	for i, value := range values {
		// Add blank line separator between items (but not before the first item)
		if i > 0 {
			io.WriteString(g.w, "\n")
		}

		switch v := value.(type) {
		case *cucarachareflex.Type:
			switch v.Kind {
			case cucarachareflex.TypeKindStruct:
				if err := g.GenerateStructCode(v); err != nil {
					return err
				}
			case cucarachareflex.TypeKindInterface:
				if err := g.GenerateInterfaceCode(v); err != nil {
					return err
				}
			case cucarachareflex.TypeKindAlias:
				if err := g.GenerateAliasCode(v); err != nil {
					return err
				}
			case cucarachareflex.TypeKindTypedef:
				if err := g.GenerateTypedefCode(v); err != nil {
					return err
				}
			default:
				return fmt.Errorf("unsupported type kind for generation: %s", v.Kind)
			}

		case *cucarachareflex.Enum:
			if err := g.GenerateEnumCode(v); err != nil {
				return err
			}
		case *cucarachareflex.Variable:
			if err := g.GenerateVariable(v); err != nil {
				return err
			}
		case *FunctionImplementation:
			if err := g.GenerateFunctionImplementation(v); err != nil {
				return err
			}
		case *MethodImplementation:
			if err := g.GenerateMethodImplementation(v); err != nil {
				return err
			}
		default:
			return fmt.Errorf("unsupported value type for generation: %T", value)
		}
	}

	return nil
}

// GenerateMultipleFromSlice generates code for multiple cucaracha/reflect values provided as a slice.
// This is a convenience variant of GenerateMultiple that accepts a slice instead of variadic arguments.
//
// See GenerateMultiple for details on supported types and error handling.
func (g *Generator) GenerateMultipleFromSlice(values []interface{}) error {
	return g.Generate(values...)
}

// formatParameters formats a slice of parameters into a comma-separated list
func formatParameters(params []*cucarachareflex.Parameter) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, param := range params {
		if param.Name != "" {
			parts = append(parts, fmt.Sprintf("%s %s", param.Name, param.Type.Name))
		} else {
			parts = append(parts, param.Type.Name)
		}
	}

	return strings.Join(parts, ", ")
}

// formatParametersWithParens formats parameters with parentheses when there are multiple values
func formatParametersWithParens(params []*cucarachareflex.Parameter) string {
	if len(params) == 0 {
		return ""
	}

	formatted := formatParameters(params)
	if len(params) > 1 {
		return "(" + formatted + ")"
	}
	return formatted
}

// toCommandName converts a struct/method name to command name (camelCase)
// e.g., "Step" -> "step", "RemoveBreakpoint" -> "removeBreakpoint"
func toCommandName(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[0:1]) + s[1:]
}

// File represents a single Go source file to be generated.
// It contains all the types, functions, methods, variables, and enums that should be
// written to the output file. File provides a builder pattern interface for constructing
// the file definition.
type File struct {
	// Package is the Go package name for this file (e.g., "debugger", "reflect").
	// This determines the package declaration at the top of the generated file.
	Package string `json:"package"`

	// Doc is an optional file-level documentation comment.
	// If present, it will be written at the beginning of the generated file.
	Doc string `json:"doc,omitempty"`

	// Imports is a list of import paths to include in this file.
	// Examples: "fmt", "encoding/json", "github.com/user/repo/pkg"
	Imports []string `json:"imports,omitempty"`

	// Types is a list of type definitions to generate (structs, interfaces, aliases).
	Types []*cucarachareflex.Type `json:"types,omitempty"`

	// Functions is a list of function implementations to generate.
	// Each includes the function signature and a template for the body.
	Functions []*FunctionImplementation `json:"functions,omitempty"`

	// Methods is a list of method implementations to generate.
	// Each includes the method signature and a template for the body.
	Methods []*MethodImplementation `json:"methods,omitempty"`

	// Variables is a list of global variables to generate.
	Variables []*cucarachareflex.Variable `json:"variables,omitempty"`

	// Enums is a list of enum type definitions to generate.
	// Usually includes additional helper methods like String(), UnmarshalJSON(), etc.
	Enums []*cucarachareflex.Enum `json:"enums,omitempty"`
}

func NewFile(pkgName string) *File {
	return &File{
		Package: pkgName,
	}
}

func (f *File) AddImport(importPath string) *File {
	f.Imports = append(f.Imports, importPath)
	return f
}

func (f *File) AddType(typ *cucarachareflex.Type) *File {
	f.Types = append(f.Types, typ)
	return f
}

func (f *File) AddFunction(fn *FunctionImplementation) *File {
	f.Functions = append(f.Functions, fn)
	return f
}

func (f *File) AddMethod(method *MethodImplementation) *File {
	f.Methods = append(f.Methods, method)
	return f
}

func (f *File) AddVariable(variable *cucarachareflex.Variable) *File {
	f.Variables = append(f.Variables, variable)
	return f
}

func (f *File) AddEnum(enum *cucarachareflex.Enum) *File {
	f.Enums = append(f.Enums, enum)
	return f
}

// GenerateFile generates code for a single file in a package.
func (g *Generator) GenerateFile(file *File) error {
	// Write file-level code generation comment
	io.WriteString(g.w, "// Code generated by codegen; DO NOT EDIT.\n\n")
	io.WriteString(g.w, "// This file was generated based on the following codegen.File:\n")

	// Marshal the File struct to JSON for documentation
	fileJSON, err := json.MarshalIndent(file, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal File struct to JSON: %w", err)
	}

	// Write the JSON with comment prefix on each line
	for _, line := range strings.Split(string(fileJSON), "\n") {
		if line != "" {
			fmt.Fprintf(g.w, "// %s\n", line)
		}
	}
	io.WriteString(g.w, "\n")

	// Write file-level documentation if available
	if file.Doc != "" {
		for _, line := range strings.Split(strings.TrimSpace(file.Doc), "\n") {
			fmt.Fprintf(g.w, "// %s\n", strings.TrimPrefix(strings.TrimSpace(line), "// "))
		}
		io.WriteString(g.w, "\n")
	}

	// Write package declaration
	fmt.Fprintf(g.w, "package %s\n\n", file.Package)

	if len(file.Enums) > 0 {
		file.AddImport("fmt")           // For error formatting in FromString function
		file.AddImport("encoding/json") // For JSON marshal/unmarshal methods
	}

	uniqueImports := utils.Set(file.Imports)

	if len(uniqueImports) > 0 {
		if len(uniqueImports) == 1 {
			for _, imp := range uniqueImports {
				fmt.Fprintf(g.w, "import %q\n\n", imp)
			}
		} else {
			io.WriteString(g.w, "import (\n")
			for _, imp := range uniqueImports {
				fmt.Fprintf(g.w, "\t%q\n", imp)
			}
			io.WriteString(g.w, ")\n\n")
		}
	}

	for _, typ := range file.Types {
		if err := g.Generate(typ); err != nil {
			return fmt.Errorf("failed to generate type '%s': %w", typ.Name, err)
		}
	}

	for _, fn := range file.Functions {
		if err := g.Generate(fn); err != nil {
			return fmt.Errorf("failed to generate function '%s' implementation: %w", fn.Function.Name, err)
		}
	}

	for _, method := range file.Methods {
		if err := g.Generate(method); err != nil {
			return fmt.Errorf("failed to generate method '%s' implementation: %w", method.Method.Name, err)
		}
	}

	for _, variable := range file.Variables {
		if err := g.Generate(variable); err != nil {
			return fmt.Errorf("failed to generate variable '%s': %w", variable.Name, err)
		}
	}

	for _, enum := range file.Enums {
		if err := g.Generate(enum); err != nil {
			return fmt.Errorf("failed to generate enum '%s': %w", enum.Type.Name, err)
		}
	}

	return nil
}

// Generate generates a Go source file at the specified output path based on the provided File metadata.
func Generate(file *File, outputPath string) error {
	tempFile := outputPath + ".tmp"

	// Create temporary output file (So that generation errors don't break existing file)
	f, err := os.Create(tempFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}

	// Create a package from the file's enums so the generator can look them up
	pkg := &cucarachareflex.Package{
		Enums: make(map[string]*cucarachareflex.Enum),
	}
	for _, enum := range file.Enums {
		pkg.Enums[enum.Type.Name] = enum
	}

	// Create a new generator and generate the file content
	generator := NewGenerator(pkg, f)
	if err := generator.GenerateFile(file); err != nil {
		f.Close()
		os.Remove(tempFile)
		return fmt.Errorf("failed to generate file content: %w", err)
	}

	f.Close() // Close before formatting

	// Make sure the file is properly formatted
	if err := formatGoFile(tempFile); err != nil {
		unformattedContent, _ := os.ReadFile(tempFile)
		os.Remove(tempFile)
		return fmt.Errorf("failed to format generated file: %w\nUnformatted content:\n%s", err, string(unformattedContent))
	}

	// Rename the temporary file to the final output path
	if err := os.Rename(tempFile, outputPath); err != nil {
		os.Remove(tempFile)
		return fmt.Errorf("failed to rename temporary file: %w", err)
	}

	return nil
}

func formatGoFile(filePath string) error {
	cmd := exec.Command("gofmt", "-w", filePath)
	return cmd.Run()
}
