package codegen

import (
	"bytes"
	"strings"
	"testing"
	"text/template"

	"github.com/Manu343726/cucaracha/pkg/reflect"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestGenerator tests the Generator functionality
func TestGenerator(t *testing.T) {
	t.Run("NewGenerator", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "testpkg",
		}
		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)

		assert.NotNil(t, gen)
		assert.Same(t, pkg, gen.pkg)
	})

	t.Run("GenerateStructCode basic struct", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "models",
			Types: map[string]*reflect.Type{
				"User": {
					Name: "User",
					Kind: reflect.TypeKindStruct,
					Doc:  "",
					Fields: []*reflect.Field{
						{
							Name: "ID",
							Type: &reflect.TypeReference{Name: "int64"},
							Doc:  "Unique identifier",
						},
						{
							Name: "Name",
							Type: &reflect.TypeReference{Name: "string"},
							Doc:  "User's full name",
							Tag:  `json:"name"`,
						},
					},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		userType := pkg.Types["User"]
		err := gen.GenerateStructCode(userType)
		code := buf.String()

		require.NoError(t, err)

		expected := `// Code generated by codegen; DO NOT EDIT.

// User is a generated struct.
type User struct {
	// Unique identifier
	ID int64
	// User's full name
	Name string ` + "`" + `json:"name"` + "`" + `
}
`
		assert.Equal(t, expected, code)
	})

	t.Run("GenerateStructCode with non-struct returns error", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"NotStruct": {
					Name: "NotStruct",
					Kind: reflect.TypeKindBasic,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateStructCode(pkg.Types["NotStruct"])

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "not a struct")
	})

	t.Run("GenerateInterfaceCode", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"Reader": {
					Name: "Reader",
					Kind: reflect.TypeKindInterface,
					Doc:  "Reader interface",
					Methods: []*reflect.Method{
						{
							Name: "Read",
							Doc:  "Reads data",
							Args: []*reflect.Parameter{
								{
									Name: "p",
									Type: &reflect.TypeReference{Name: "[]byte"},
								},
							},
							Results: []*reflect.Parameter{
								{
									Name: "n",
									Type: &reflect.TypeReference{Name: "int"},
								},
								{
									Type: &reflect.TypeReference{Name: "error"},
								},
							},
						},
						{
							Name: "Close",
							Doc:  "Closes the reader",
							Args: []*reflect.Parameter{},
							Results: []*reflect.Parameter{
								{Type: &reflect.TypeReference{Name: "error"}},
							},
						},
					},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		readerType := pkg.Types["Reader"]
		err := gen.GenerateInterfaceCode(readerType)
		code := buf.String()

		require.NoError(t, err)

		expected := `// Code generated by codegen; DO NOT EDIT.

// Reader interface
type Reader interface {
	// Reads data
	Read(p []byte) (n int, error)
	// Closes the reader
	Close() error
}
`
		assert.Equal(t, expected, code)
	})

	t.Run("GenerateInterfaceCode with non-interface returns error", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"NotInterface": {
					Name: "NotInterface",
					Kind: reflect.TypeKindStruct,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateInterfaceCode(pkg.Types["NotInterface"])

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "not an interface")
	})

	t.Run("GenerateFunctionSignature", func(t *testing.T) {
		tests := []struct {
			name     string
			fn       *reflect.Function
			expected string
		}{
			{
				name: "simple function",
				fn: &reflect.Function{
					Name: "Add",
					Args: []*reflect.Parameter{
						{Name: "a", Type: &reflect.TypeReference{Name: "int"}},
						{Name: "b", Type: &reflect.TypeReference{Name: "int"}},
					},
					Results: []*reflect.Parameter{
						{Type: &reflect.TypeReference{Name: "int"}},
					},
				},
				expected: "func Add(a int, b int) int",
			},
			{
				name: "function with multiple return values",
				fn: &reflect.Function{
					Name: "Read",
					Args: []*reflect.Parameter{
						{Name: "p", Type: &reflect.TypeReference{Name: "[]byte"}},
					},
					Results: []*reflect.Parameter{
						{Name: "n", Type: &reflect.TypeReference{Name: "int"}},
						{Type: &reflect.TypeReference{Name: "error"}},
					},
				},
				expected: "func Read(p []byte) (n int, error)",
			},
			{
				name: "function with no arguments",
				fn: &reflect.Function{
					Name: "Now",
					Args: []*reflect.Parameter{},
					Results: []*reflect.Parameter{
						{Type: &reflect.TypeReference{Name: "time.Time"}},
					},
				},
				expected: "func Now() time.Time",
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				buf.Reset()
				gen.GenerateFunctionSignature(tt.fn)
				sig := buf.String()
				assert.Equal(t, tt.expected, sig)
			})
		}
	})

	t.Run("GenerateEnumCode", func(t *testing.T) {
		statusType := &reflect.Type{
			Name:         "Status",
			Kind:         reflect.TypeKindTypedef,
			Doc:          "Status enum for items",
			OriginalType: &reflect.TypeReference{Name: "int"},
		}
		enum := &reflect.Enum{
			Type:         &reflect.TypeReference{Name: "Status", Type: statusType},
			StringMethod: true,
			Values: []*reflect.Constant{
				{Name: "StatusActive", Doc: "Item is active", Value: &reflect.Value{Value: "iota", Type: &reflect.TypeReference{Name: "Status", Type: statusType}}},
				{Name: "StatusInactive", Doc: "Item is inactive", Value: &reflect.Value{Type: &reflect.TypeReference{Name: "Status", Type: statusType}}},
				{Name: "StatusPending", Doc: "Item is pending", Value: &reflect.Value{Type: &reflect.TypeReference{Name: "Status", Type: statusType}}},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		gen.GenerateEnumCode(enum)
		code := buf.String()

		// Note: The generated code includes String(), FromString(), MarshalJSON, UnmarshalJSON, and values map
		// We'll just verify the basic structure is present
		assert.Contains(t, code, "// Code generated by codegen; DO NOT EDIT.")
		assert.Contains(t, code, "type Status int")
		assert.Contains(t, code, "StatusActive Status = iota")
		assert.Contains(t, code, "StatusInactive")
		assert.Contains(t, code, "StatusPending")
		assert.Contains(t, code, "func (e Status) String() string {")
	})

	t.Run("GenerateEnumCode without String method", func(t *testing.T) {
		stringType := &reflect.Type{Name: "string", Kind: reflect.TypeKindBasic}
		colorType := &reflect.Type{
			Name:         "Color",
			Kind:         reflect.TypeKindTypedef,
			OriginalType: &reflect.TypeReference{Name: "string", Type: stringType},
		}
		enum := &reflect.Enum{
			Type:         &reflect.TypeReference{Name: "Color", Type: colorType},
			StringMethod: false,
			Values: []*reflect.Constant{
				{Name: "ColorRed", Value: &reflect.Value{Value: "iota", Type: &reflect.TypeReference{Name: "Color", Type: colorType}}},
				{Name: "ColorGreen", Value: &reflect.Value{Type: &reflect.TypeReference{Name: "Color", Type: colorType}}},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		gen.GenerateEnumCode(enum)
		code := buf.String()

		// Note: The generated code includes String(), FromString(), MarshalJSON, UnmarshalJSON, and values map
		// We'll just verify the basic structure is present
		assert.Contains(t, code, "// Code generated by codegen; DO NOT EDIT.")
		assert.Contains(t, code, "type Color string")
		assert.Contains(t, code, "ColorRed Color = iota")
		assert.Contains(t, code, "ColorGreen")
		assert.Contains(t, code, "func (e Color) String() string {")
	})

	t.Run("GenerateBuilderMethod", func(t *testing.T) {
		typ := &reflect.Type{
			Name: "Config",
			Kind: reflect.TypeKindStruct,
			Fields: []*reflect.Field{
				{
					Name: "Host",
					Type: &reflect.TypeReference{Name: "string"},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateBuilderMethod(typ)
		require.NoError(t, err)
		code := buf.String()

		expected := `// NewConfig creates a new Config instance.
func NewConfig() *Config {
	return &Config{}
}
`
		assert.Equal(t, expected, code)
	})

	t.Run("GenerateBuilderMethod with non-struct returns error", func(t *testing.T) {
		typ := &reflect.Type{
			Name: "NotStruct",
			Kind: reflect.TypeKindInterface,
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateBuilderMethod(typ)

		assert.Error(t, err)
	})
}

// TestFormatParameters tests the formatParameters helper
func TestFormatParameters(t *testing.T) {
	t.Run("empty parameters", func(t *testing.T) {
		result := formatParameters([]*reflect.Parameter{})
		assert.Empty(t, result)
	})

	t.Run("single parameter with name", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Name: "x", Type: &reflect.TypeReference{Name: "int"}},
		}
		result := formatParameters(params)
		assert.Equal(t, "x int", result)
	})

	t.Run("multiple parameters with names", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Name: "x", Type: &reflect.TypeReference{Name: "int"}},
			{Name: "y", Type: &reflect.TypeReference{Name: "string"}},
		}
		result := formatParameters(params)
		assert.Equal(t, "x int, y string", result)
	})

	t.Run("parameter without name", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Type: &reflect.TypeReference{Name: "error"}},
		}
		result := formatParameters(params)
		assert.Equal(t, "error", result)
	})

	t.Run("mixed named and unnamed", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Name: "p", Type: &reflect.TypeReference{Name: "[]byte"}},
			{Type: &reflect.TypeReference{Name: "int"}},
			{Type: &reflect.TypeReference{Name: "error"}},
		}
		result := formatParameters(params)
		assert.Equal(t, "p []byte, int, error", result)
	})
}

// TestToCommandName tests the toCommandName helper
func TestToCommandName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"Apply", "apply"},
		{"Step", "step"},
		{"Continue", "continue"},
		{"SetBreakpoint", "setBreakpoint"},
		{"RemoveBreakpoint", "removeBreakpoint"},
		{"GetStackTrace", "getStackTrace"},
		{"a", "a"},
		{"A", "a"},
		{"", ""},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := toCommandName(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

// TestGeneratorIntegration tests complex generator scenarios
func TestGeneratorIntegration(t *testing.T) {
	t.Run("Generate complete package", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "debugger",
			Types: map[string]*reflect.Type{
				"CommandID": {
					Name: "CommandID",
					Kind: reflect.TypeKindBasic,
				},
				"Breakpoint": {
					Name: "Breakpoint",
					Kind: reflect.TypeKindStruct,
					Doc:  "Breakpoint represents a debugger breakpoint.",
					Fields: []*reflect.Field{
						{
							Name: "ID",
							Type: &reflect.TypeReference{Name: "CommandID"},
							Doc:  "Breakpoint identifier",
						},
						{
							Name: "Location",
							Type: &reflect.TypeReference{Name: "string"},
							Doc:  "File:line location",
						},
					},
				},
			},
		}

		var structBuf bytes.Buffer
		gen := NewGenerator(pkg, &structBuf)
		bpType := pkg.Types["Breakpoint"]
		err := gen.GenerateStructCode(bpType)
		require.NoError(t, err)
		structCode := structBuf.String()

		var builderBuf bytes.Buffer
		gen2 := NewGenerator(pkg, &builderBuf)
		err = gen2.GenerateBuilderMethod(bpType)
		require.NoError(t, err)
		builderCode := builderBuf.String()

		expectedStruct := `// Code generated by codegen; DO NOT EDIT.

// Breakpoint represents a debugger breakpoint.
type Breakpoint struct {
	// Breakpoint identifier
	ID CommandID
	// File:line location
	Location string
}
`
		expectedBuilder := `// NewBreakpoint creates a new Breakpoint instance.
func NewBreakpoint() *Breakpoint {
	return &Breakpoint{}
}
`
		assert.Equal(t, expectedStruct, structCode)
		assert.Equal(t, expectedBuilder, builderCode)
	})

	t.Run("Generate interface with complex signatures", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"Debugger": {
					Name: "Debugger",
					Kind: reflect.TypeKindInterface,
					Doc:  "Debugger interface",
					Methods: []*reflect.Method{
						{
							Name: "Execute",
							Doc:  "Execute a command",
							Args: []*reflect.Parameter{
								{Name: "cmd", Type: &reflect.TypeReference{Name: "Command"}},
								{Name: "ctx", Type: &reflect.TypeReference{Name: "context.Context"}},
							},
							Results: []*reflect.Parameter{
								{Type: &reflect.TypeReference{Name: "error"}},
							},
						},
						{
							Name: "GetState",
							Doc:  "Get debugger state",
							Args: []*reflect.Parameter{},
							Results: []*reflect.Parameter{
								{Type: &reflect.TypeReference{Name: "*State"}},
								{Type: &reflect.TypeReference{Name: "error"}},
							},
						},
					},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		debuggerType := pkg.Types["Debugger"]

		err := gen.GenerateInterfaceCode(debuggerType)
		require.NoError(t, err)
		code := buf.String()

		expected := `// Code generated by codegen; DO NOT EDIT.

// Debugger interface
type Debugger interface {
	// Execute a command
	Execute(cmd Command, ctx context.Context) error
	// Get debugger state
	GetState() (*State, error)
}
`
		assert.Equal(t, expected, code)
	})
}

// BenchmarkGeneratorStructCode benchmarks code generation for structs
func BenchmarkGeneratorStructCode(b *testing.B) {
	typ := &reflect.Type{
		Name: "TestStruct",
		Kind: reflect.TypeKindStruct,
		Doc:  "Test struct",
		Fields: []*reflect.Field{
			{Name: "ID", Type: &reflect.TypeReference{Name: "int64"}, Doc: "ID field"},
			{Name: "Name", Type: &reflect.TypeReference{Name: "string"}, Doc: "Name field"},
			{Name: "Email", Type: &reflect.TypeReference{Name: "string"}, Doc: "Email field"},
		},
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		_ = gen.GenerateStructCode(typ)
	}
}

// BenchmarkGeneratorInterfaceCode benchmarks code generation for interfaces
func BenchmarkGeneratorInterfaceCode(b *testing.B) {
	typ := &reflect.Type{
		Name: "Reader",
		Kind: reflect.TypeKindInterface,
		Methods: []*reflect.Method{
			{
				Name: "Read",
				Args: []*reflect.Parameter{
					{Name: "p", Type: &reflect.TypeReference{Name: "[]byte"}},
				},
				Results: []*reflect.Parameter{
					{Name: "n", Type: &reflect.TypeReference{Name: "int"}},
					{Type: &reflect.TypeReference{Name: "error"}},
				},
			},
		},
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		_ = gen.GenerateInterfaceCode(typ)
	}
}

// TestGenerateValue tests the GenerateValue function with various types
func TestGenerateValue(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	t.Run("nil value", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(nil))
		require.NoError(t, err)
		assert.Equal(t, "nil", buf.String())
	})

	t.Run("string value", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue("hello"))
		require.NoError(t, err)
		assert.Equal(t, `"hello"`, buf.String())
	})

	t.Run("bool value true", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(true))
		require.NoError(t, err)
		assert.Equal(t, "true", buf.String())
	})

	t.Run("bool value false", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(false))
		require.NoError(t, err)
		assert.Equal(t, "false", buf.String())
	})

	t.Run("int value", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(42))
		require.NoError(t, err)
		assert.Equal(t, "42", buf.String())
	})

	t.Run("negative int value", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(-42))
		require.NoError(t, err)
		assert.Equal(t, "-42", buf.String())
	})

	t.Run("float value", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(3.14))
		require.NoError(t, err)
		assert.Contains(t, buf.String(), "3.14")
	})

	t.Run("empty slice", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue([]int{}))
		require.NoError(t, err)
		assert.Equal(t, "[]int{}", buf.String())
	})

	t.Run("slice with values", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue([]int{1, 2, 3}))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "[]int{")
		assert.Contains(t, code, "1,")
		assert.Contains(t, code, "2,")
		assert.Contains(t, code, "3")
		assert.Contains(t, code, "}")
	})

	t.Run("slice of strings", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue([]string{"a", "b", "c"}))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "[]string{")
		assert.Contains(t, code, `"a"`)
		assert.Contains(t, code, `"b"`)
		assert.Contains(t, code, `"c"`)
	})

	t.Run("empty map", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(map[string]int{}))
		require.NoError(t, err)
		assert.Equal(t, "map[string]int{}", buf.String())
	})

	t.Run("map with values", func(t *testing.T) {
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(map[string]int{"a": 1, "b": 2}))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "map[string]int{")
		assert.Contains(t, code, `"a": 1`)
		assert.Contains(t, code, `"b": 2`)
		assert.Contains(t, code, "}")
	})

	t.Run("nil pointer", func(t *testing.T) {
		var p *int
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(p))
		require.NoError(t, err)
		assert.Equal(t, "nil", buf.String())
	})

	t.Run("pointer to value", func(t *testing.T) {
		val := 42
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(&val))
		require.NoError(t, err)
		assert.Equal(t, "42", buf.String())
	})
}

// TestGenerateValueStruct tests GenerateValue with struct types
func TestGenerateValueStruct(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	type Point struct {
		X int
		Y int
	}

	t.Run("simple struct", func(t *testing.T) {
		p := Point{X: 1, Y: 2}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(p))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "Point{")
		assert.Contains(t, code, "X: 1")
		assert.Contains(t, code, "Y: 2")
		assert.Contains(t, code, "}")
	})

	t.Run("struct with zero values", func(t *testing.T) {
		p := Point{X: 0, Y: 0}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(p))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "Point{")
		assert.Contains(t, code, "X: 0")
		assert.Contains(t, code, "Y: 0")
	})
}

// TestGenerateValueNested tests GenerateValue with nested structures
func TestGenerateValueNested(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	type Coordinate struct {
		Latitude  float64
		Longitude float64
	}

	type Location struct {
		Name       string
		Coordinate Coordinate
	}

	t.Run("nested struct", func(t *testing.T) {
		loc := Location{
			Name: "TestPlace",
			Coordinate: Coordinate{
				Latitude:  40.7128,
				Longitude: -74.0060,
			},
		}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(loc))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "Location{")
		assert.Contains(t, code, `Name: "TestPlace"`)
		assert.Contains(t, code, "Coordinate{")
		assert.Contains(t, code, "Latitude:")
		assert.Contains(t, code, "Longitude:")
	})
}

// TestGenerateValueArray tests GenerateValue with array types
func TestGenerateValueArray(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	t.Run("array of ints", func(t *testing.T) {
		arr := [3]int{10, 20, 30}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(arr))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "[3]int{")
		assert.Contains(t, code, "10")
		assert.Contains(t, code, "20")
		assert.Contains(t, code, "30")
	})

	t.Run("empty array", func(t *testing.T) {
		arr := [0]int{}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(arr))
		require.NoError(t, err)
		assert.Equal(t, "[0]int{}", buf.String())
	})
}

// TestGenerateValueComplexNested tests GenerateValue with more complex nested types
func TestGenerateValueComplexNested(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	type User struct {
		ID    int
		Name  string
		Tags  []string
		Score float64
	}

	t.Run("struct with slice field", func(t *testing.T) {
		user := User{
			ID:    1,
			Name:  "Alice",
			Tags:  []string{"admin", "user"},
			Score: 95.5,
		}
		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateValue(reflect.NewValue(user))
		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "User{")
		assert.Contains(t, code, "ID: 1")
		assert.Contains(t, code, `Name: "Alice"`)
		assert.Contains(t, code, "Tags:")
		assert.Contains(t, code, "[]string{")
		assert.Contains(t, code, `"admin"`)
		assert.Contains(t, code, `"user"`)
		assert.Contains(t, code, "Score: 95.5")
	})
}

// TestGenerateFunctionImplementation tests the GenerateFunctionImplementation functionality
func TestGenerateFunctionImplementation(t *testing.T) {
	t.Run("simple function with basic template", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Add",
			Args: []*reflect.Parameter{
				{Name: "a", Type: &reflect.TypeReference{Name: "int"}},
				{Name: "b", Type: &reflect.TypeReference{Name: "int"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "int"}},
			},
		}

		templateBody := "return a + b"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		expected := `func Add(a int, b int) int {
	return a + b
}
`
		assert.Equal(t, expected, code)
	})

	t.Run("function with context data", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Greet",
			Args: []*reflect.Parameter{
				{Name: "name", Type: &reflect.TypeReference{Name: "string"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "string"}},
			},
		}

		templateBody := `return "Hello, " + name + "! Welcome to {{.Place}}"`
		context := map[string]interface{}{
			"Place": "Go",
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "func Greet(name string) string")
		assert.Contains(t, code, `return "Hello, " + name + "! Welcome to Go"`)
	})

	t.Run("function with multiline template", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Process",
			Args: []*reflect.Parameter{
				{Name: "data", Type: &reflect.TypeReference{Name: "[]byte"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "error"}},
			},
		}

		templateBody := `if len(data) == 0 {
		return errors.New("data cannot be empty")
	}
	return nil`

		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "func Process(data []byte) error {")
		assert.Contains(t, code, `if len(data) == 0 {`)
		assert.Contains(t, code, `return errors.New("data cannot be empty")`)
		assert.Contains(t, code, `return nil`)
	})

	t.Run("function with documentation", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Calculate",
			Doc:  "Calculate the sum of two integers",
			Args: []*reflect.Parameter{
				{Name: "x", Type: &reflect.TypeReference{Name: "int"}},
				{Name: "y", Type: &reflect.TypeReference{Name: "int"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "int"}},
			},
		}

		templateBody := "return x + y"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementationWithOpts(
			&FunctionImplementation{
				Function:        fn,
				BodyTemplate:    templateBody,
				TemplateContext: context,
			},
			FunctionGenerationOpts{WriteDocs: true},
		)

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "// Calculate the sum of two integers")
		assert.Contains(t, code, "func Calculate(x int, y int) int {")
		assert.Contains(t, code, "return x + y")
	})

	t.Run("function with indentation", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Test",
			Args: []*reflect.Parameter{},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "bool"}},
			},
		}

		templateBody := "return true"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementationWithOpts(
			&FunctionImplementation{
				Function:        fn,
				BodyTemplate:    templateBody,
				TemplateContext: context,
			},
			FunctionGenerationOpts{IndentLevel: 1},
		)

		require.NoError(t, err)
		code := buf.String()

		// Should start with a tab for indent level 1
		lines := strings.Split(code, "\n")
		assert.True(t, strings.HasPrefix(lines[0], "\t"))
		assert.True(t, strings.HasPrefix(lines[1], "\t\t"))
	})

	t.Run("function with custom template functions", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Format",
			Args: []*reflect.Parameter{
				{Name: "value", Type: &reflect.TypeReference{Name: "string"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "string"}},
			},
		}

		templateBody := `return {{.Value | Upper}}`
		context := map[string]interface{}{
			"Value": "hello",
		}

		customFuncs := template.FuncMap{
			"Upper": strings.ToUpper,
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementationWithOpts(
			&FunctionImplementation{
				Function:        fn,
				BodyTemplate:    templateBody,
				TemplateContext: context,
			},
			FunctionGenerationOpts{TemplateFuncs: customFuncs},
		)

		require.NoError(t, err)
		code := buf.String()

		// The template should use the Upper function to convert the value
		assert.Contains(t, code, `return HELLO`)
	})

	t.Run("function with template range", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "PrintItems",
			Args: []*reflect.Parameter{
				{Name: "items", Type: &reflect.TypeReference{Name: "[]string"}},
			},
			Results: []*reflect.Parameter{},
		}

		templateBody := `{{range .Items}}fmt.Println("Item: " + "{{.}}")
	{{end}}`

		context := map[string]interface{}{
			"Items": []string{"apple", "banana"},
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, `fmt.Println("Item: " + "apple")`)
		assert.Contains(t, code, `fmt.Println("Item: " + "banana")`)
	})

	t.Run("function with template conditional", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "Validate",
			Args: []*reflect.Parameter{
				{Name: "value", Type: &reflect.TypeReference{Name: "int"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "bool"}},
			},
		}

		templateBody := `{{if gt .Min 0}}if value < {{.Min}} {
		return false
	}
	{{end}}return true`

		context := map[string]interface{}{
			"Min": 10,
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "if value < 10 {")
		assert.Contains(t, code, "return false")
		assert.Contains(t, code, "return true")
	})

	t.Run("function with invalid template", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "BadTemplate",
			Args: []*reflect.Parameter{},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "error"}},
			},
		}

		invalidTemplate := "{{.UnclosedBrace"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    invalidTemplate,
			TemplateContext: context,
		})

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "failed to parse function body template")
	})

	t.Run("function with template execution error", func(t *testing.T) {
		fn := &reflect.Function{
			Name:    "ErrorTemplate",
			Args:    []*reflect.Parameter{},
			Results: []*reflect.Parameter{},
		}

		// Template that tries to access a non-existent field
		templateBody := "{{.NonExistentField}}"
		context := map[string]interface{}{
			"OtherField": "value",
		}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		// Note: This should not error because undefined fields are replaced with empty string in text/template
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})
		require.NoError(t, err)
	})

	t.Run("function with no arguments no results", func(t *testing.T) {
		fn := &reflect.Function{
			Name:    "DoNothing",
			Args:    []*reflect.Parameter{},
			Results: []*reflect.Parameter{},
		}

		templateBody := "// This function does nothing"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "func DoNothing() {")
		assert.Contains(t, code, "// This function does nothing")
	})

	t.Run("function with multiple return values", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "ReadFile",
			Args: []*reflect.Parameter{
				{Name: "filename", Type: &reflect.TypeReference{Name: "string"}},
			},
			Results: []*reflect.Parameter{
				{Name: "data", Type: &reflect.TypeReference{Name: "[]byte"}},
				{Type: &reflect.TypeReference{Name: "error"}},
			},
		}

		templateBody := `return ioutil.ReadFile(filename)`
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        fn,
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "func ReadFile(filename string) (data []byte, error) {")
		assert.Contains(t, code, "return ioutil.ReadFile(filename)")
	})

	t.Run("function documentation with multiline comment", func(t *testing.T) {
		fn := &reflect.Function{
			Name: "ComplexFunc",
			Doc: `// This function does something complex
// It has multiple lines of documentation
// And provides useful information`,
			Args:    []*reflect.Parameter{},
			Results: []*reflect.Parameter{},
		}

		templateBody := "fmt.Println(\"complex\")"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementationWithOpts(
			&FunctionImplementation{
				Function:        fn,
				BodyTemplate:    templateBody,
				TemplateContext: context,
			},
			FunctionGenerationOpts{WriteDocs: true},
		)

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "// This function does something complex")
		assert.Contains(t, code, "// It has multiple lines of documentation")
		assert.Contains(t, code, "// And provides useful information")
	})
}

// TestGenerateMethodImplementation tests the MethodImplementation functionality
func TestGenerateMethodImplementation(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	t.Run("simple method with basic template", func(t *testing.T) {
		method := &reflect.Method{
			Name:     "Read",
			Receiver: &reflect.Parameter{Type: &reflect.TypeReference{Name: "Reader"}},
			Args: []*reflect.Parameter{
				{Name: "p", Type: &reflect.TypeReference{Name: "[]byte"}},
			},
			Results: []*reflect.Parameter{
				{Type: &reflect.TypeReference{Name: "int"}},
				{Type: &reflect.TypeReference{Name: "error"}},
			},
		}

		templateBody := "return len(p), nil"
		context := map[string]interface{}{}

		var buf bytes.Buffer
		gen := NewGenerator(&reflect.Package{}, &buf)
		err := gen.GenerateFunctionImplementation(&FunctionImplementation{
			Function:        &reflect.Function{Name: method.Name},
			BodyTemplate:    templateBody,
			TemplateContext: context,
		})

		require.NoError(t, err)
		code := buf.String()
		assert.Contains(t, code, "func Read() {")
		assert.Contains(t, code, "return len(p), nil")
	})
}

// TestGenerateMultiple tests the Generate functionality
func TestGenerateMultiple(t *testing.T) {
	t.Skip("GenerateValue requires proper type information; these tests need refactoring")

	t.Run("generate struct and interface", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "models",
			Types: map[string]*reflect.Type{
				"Reader": {
					Name: "Reader",
					Kind: reflect.TypeKindInterface,
					Doc:  "Reader interface",
					Methods: []*reflect.Method{
						{
							Name: "Read",
							Args: []*reflect.Parameter{
								{Name: "p", Type: &reflect.TypeReference{Name: "[]byte"}},
							},
							Results: []*reflect.Parameter{
								{Type: &reflect.TypeReference{Name: "int"}},
								{Type: &reflect.TypeReference{Name: "error"}},
							},
						},
					},
				},
				"Buffer": {
					Name: "Buffer",
					Kind: reflect.TypeKindStruct,
					Doc:  "Buffer type",
					Fields: []*reflect.Field{
						{
							Name: "Data",
							Type: &reflect.TypeReference{Name: "[]byte"},
							Doc:  "Buffer data",
						},
					},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)

		// Generate both types
		err := gen.Generate(pkg.Types["Reader"], pkg.Types["Buffer"])
		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "type Reader interface {")
		assert.Contains(t, code, "Read(p []byte) (int, error)")
		assert.Contains(t, code, "type Buffer struct {")
		assert.Contains(t, code, "Data []byte")
	})

	t.Run("generate multiple enums", func(t *testing.T) {
		statusType := &reflect.Type{
			Name: "Status",
			Kind: reflect.TypeKindTypedef,
		}
		pkg := &reflect.Package{
			Name: "status",
			Enums: map[string]*reflect.Enum{
				"Status": {
					Type: &reflect.TypeReference{Name: "int", Type: &reflect.Type{Name: "int", Kind: reflect.TypeKindBasic}},
					Values: []*reflect.Constant{
						{
							Name:  "StatusPending",
							Doc:   "Pending status",
							Value: &reflect.Value{Value: "iota", Type: &reflect.TypeReference{Name: "Status", Type: statusType}},
						},
						{
							Name:  "StatusComplete",
							Doc:   "Complete status",
							Value: &reflect.Value{Type: &reflect.TypeReference{Name: "Status", Type: statusType}},
						},
					},
					StringMethod: true,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)

		enum := pkg.Enums["Status"]
		err := gen.Generate(enum, enum)
		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "type Status int")
		assert.Contains(t, code, "const (")
		assert.Contains(t, code, "StatusPending Status = iota")
		assert.Contains(t, code, "func (e Status) String() string {")
	})
}

// TestGenerateAliasCode tests alias generation
func TestGenerateAliasCode(t *testing.T) {
	t.Run("generate type alias", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "types",
			Types: map[string]*reflect.Type{
				"UserID": {
					Name: "UserID",
					Kind: reflect.TypeKindAlias,
					Doc:  "UserID is a unique identifier for users",
					Elem: &reflect.TypeReference{Name: "int64"},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateAliasCode(pkg.Types["UserID"])

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "// UserID is a unique identifier for users")
		assert.Contains(t, code, "type UserID = int64")
	})

	t.Run("error when type is not an alias", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"NotAlias": {
					Name: "NotAlias",
					Kind: reflect.TypeKindBasic,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateAliasCode(pkg.Types["NotAlias"])

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "not an alias")
	})
}

// TestGenerateTypedefCode tests typedef generation
func TestGenerateTypedefCode(t *testing.T) {
	t.Run("generate type typedef", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "types",
			Types: map[string]*reflect.Type{
				"UserID": {
					Name: "UserID",
					Kind: reflect.TypeKindTypedef,
					Doc:  "UserID is a unique identifier for users",
					Elem: &reflect.TypeReference{Name: "int64"},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateTypedefCode(pkg.Types["UserID"])

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "// UserID is a unique identifier for users")
		assert.Contains(t, code, "type UserID int64")
	})

	t.Run("error when type is not a typedef", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"NotTypedef": {
					Name: "NotTypedef",
					Kind: reflect.TypeKindBasic,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateTypedefCode(pkg.Types["NotTypedef"])

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "not a typedef")
	})
}

// TestGenerateBuilderMethod tests builder method generation
func TestGenerateBuilderMethod(t *testing.T) {
	t.Run("generate builder for struct", func(t *testing.T) {
		pkg := &reflect.Package{
			Name: "models",
			Types: map[string]*reflect.Type{
				"User": {
					Name: "User",
					Kind: reflect.TypeKindStruct,
					Fields: []*reflect.Field{
						{
							Name: "ID",
							Type: &reflect.TypeReference{Name: "int64"},
						},
						{
							Name: "Name",
							Type: &reflect.TypeReference{Name: "string"},
						},
					},
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateBuilderMethod(pkg.Types["User"])

		require.NoError(t, err)
		code := buf.String()

		assert.Contains(t, code, "// NewUser creates a new User instance.")
		assert.Contains(t, code, "func NewUser() *User {")
		assert.Contains(t, code, "return &User{}")
	})

	t.Run("error when type is not a struct", func(t *testing.T) {
		pkg := &reflect.Package{
			Types: map[string]*reflect.Type{
				"ReadInterface": {
					Name: "ReadInterface",
					Kind: reflect.TypeKindInterface,
				},
			},
		}

		var buf bytes.Buffer
		gen := NewGenerator(pkg, &buf)
		err := gen.GenerateBuilderMethod(pkg.Types["ReadInterface"])

		assert.Error(t, err)
		assert.Contains(t, err.Error(), "not a struct")
	})
}

// TestFormatters tests the parameter and return type formatting
func TestFormatters(t *testing.T) {
	t.Run("formatParameters with named parameters", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Name: "a", Type: &reflect.TypeReference{Name: "int"}},
			{Name: "b", Type: &reflect.TypeReference{Name: "string"}},
		}

		result := formatParameters(params)
		assert.Equal(t, "a int, b string", result)
	})

	t.Run("formatParameters with unnamed parameters", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Type: &reflect.TypeReference{Name: "error"}},
		}

		result := formatParameters(params)
		assert.Equal(t, "error", result)
	})

	t.Run("formatParameters with empty list", func(t *testing.T) {
		params := []*reflect.Parameter{}

		result := formatParameters(params)
		assert.Equal(t, "", result)
	})

	t.Run("formatParametersWithParens with single return", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Type: &reflect.TypeReference{Name: "error"}},
		}

		result := formatParametersWithParens(params)
		assert.Equal(t, "error", result)
	})

	t.Run("formatParametersWithParens with multiple returns", func(t *testing.T) {
		params := []*reflect.Parameter{
			{Type: &reflect.TypeReference{Name: "string"}},
			{Type: &reflect.TypeReference{Name: "error"}},
		}

		result := formatParametersWithParens(params)
		assert.Equal(t, "(string, error)", result)
	})

	t.Run("toCommandName converts case correctly", func(t *testing.T) {
		tests := []struct {
			input    string
			expected string
		}{
			{"Step", "step"},
			{"RemoveBreakpoint", "removeBreakpoint"},
			{"Execute", "execute"},
			{"API", "aPI"},
			{"", ""},
		}

		for _, tt := range tests {
			result := toCommandName(tt.input)
			assert.Equal(t, tt.expected, result, "input: %s", tt.input)
		}
	})
}
