//go:generate go run generator.go -out zz_execute_generated.go -api api.go -docs-out zz_commands_documentation_schema.go -enum-out zz_commands_enum_generated.go -structs-out zz_commands_structs_generated.go

package debugger

import (
	"encoding/json"
	"fmt"
)

// Supporting JSON marshaling for DebuggerCommandId
func (c DebuggerCommandId) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.String())
}

func (c *DebuggerCommandId) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	val, err := DebuggerCommandIdFromString(s)
	if err != nil {
		return err
	}
	*c = val
	return nil
}

// Controls the behavior of the Step command
type StepMode int

const (
	// Step one source line (steps into function calls)
	StepModeInto StepMode = iota
	// Step one source line, stepping over function calls
	StepModeOver
	// Step out of the current function
	StepModeOut
)

func (s StepMode) String() string {
	switch s {
	case StepModeInto:
		return "into"
	case StepModeOver:
		return "over"
	case StepModeOut:
		return "out"
	default:
		return "unknown"
	}
}

func StepModeFromString(s string) (StepMode, error) {
	switch s {
	case "into":
		return StepModeInto, nil
	case "over":
		return StepModeOver, nil
	case "out":
		return StepModeOut, nil
	default:
		return 0, fmt.Errorf("unknown StepMode: \"%s\"", s)
	}
}

func (s StepMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

func (s *StepMode) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := StepModeFromString(str)
	if err != nil {
		return err
	}
	*s = val
	return nil
}

type StepCountMode int

const (
	// Count by instructions
	StepCountInstructions StepCountMode = iota
	// Count by source lines
	StepCountSourceLines
)

func (s StepCountMode) String() string {
	switch s {
	case StepCountInstructions:
		return "instructions"
	case StepCountSourceLines:
		return "sourceLines"
	default:
		return "unknown"
	}
}

func StepCountModeFromString(s string) (StepCountMode, error) {
	switch s {
	case "instructions":
		return StepCountInstructions, nil
	case "sourceLines":
		return StepCountSourceLines, nil
	default:
		return 0, fmt.Errorf("unknown StepCountMode: \"%s\"", s)
	}
}

func (s StepCountMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

func (s *StepCountMode) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := StepCountModeFromString(str)
	if err != nil {
		return err
	}
	*s = val
	return nil
}

// CommandBasedDebugger is an interface to interact with the debugger in the UI using command structures.
// It differs from the high-level Debugger interface by processing commands through a command/result pattern
// instead of direct method calls.
type CommandBasedDebugger interface {
	// Sends a command to the debugger and returns the result
	Execute(cmd *DebuggerCommand) (*DebuggerCommandResult, error)

	// Sets a callback to receive debugger events
	SetEventCallback(callback DebuggerEventCallback)

	// Resets the debugger to its initial state
	Reset() *ExecutionResult

	// Restarts the debugger (reset + continue)
	Restart() *ExecutionResult
}

type commandBasedDebuggerAdapter struct {
	debugger Debugger
}

// Returns a CommandBasedDebugger that wraps a regular Debugger implementation
func MakeCommandBased(debugger Debugger) CommandBasedDebugger {
	return &commandBasedDebuggerAdapter{debugger: debugger}
}

func (d *commandBasedDebuggerAdapter) SetEventCallback(callback DebuggerEventCallback) {
	d.debugger.SetEventCallback(callback)
}

// Execute is now generated by the go:generate tool
// This method is auto-generated from the DebuggerCommands interface
// See: zz_execute_generated.go

func (d *commandBasedDebuggerAdapter) Reset() *ExecutionResult {
	return d.debugger.Reset()
}

func (d *commandBasedDebuggerAdapter) Restart() *ExecutionResult {
	return d.debugger.Restart()
}
