// Code generated by codegen; DO NOT EDIT.

package debugger

import (
	"encoding/json"
	"fmt"
)

// Code generated by codegen; DO NOT EDIT.

// DebuggerCommand represents a debugger command with its arguments
type DebuggerCommand struct {
	// Unique ID for this command instance
	Id uint64 `json:"id"`
	// Type of command
	Command DebuggerCommandId `json:"command"`
	// Command arguments for Step command
	StepArgs *StepArgs `json:"stepargs"`
	// Command arguments for Break command
	BreakArgs *BreakArgs `json:"breakargs"`
	// Command arguments for Watch command
	WatchArgs *WatchArgs `json:"watchargs"`
	// Command arguments for RemoveBreakpoint command
	RemoveBreakpointArgs *RemoveBreakpointArgs `json:"removebreakpointargs"`
	// Command arguments for RemoveWatchpoint command
	RemoveWatchpointArgs *RemoveWatchpointArgs `json:"removewatchpointargs"`
	// Command arguments for Disasm command
	DisasmArgs *DisasmArgs `json:"disasmargs"`
	// Command arguments for Memory command
	MemoryArgs *MemoryArgs `json:"memoryargs"`
	// Command arguments for Source command
	SourceArgs *SourceArgs `json:"sourceargs"`
	// Command arguments for CurrentSource command
	CurrentSourceArgs *CurrentSourceArgs `json:"currentsourceargs"`
	// Command arguments for Eval command
	EvalArgs *EvalArgs `json:"evalargs"`
	// Command arguments for Info command
	InfoArgs *InfoArgs `json:"infoargs"`
	// Command arguments for Symbols command
	SymbolsArgs *SymbolsArgs `json:"symbolsargs"`
	// Command arguments for LoadSystem command
	LoadSystemArgs *LoadSystemArgs `json:"loadsystemargs"`
	// Command arguments for LoadProgram command
	LoadProgramArgs *LoadProgramArgs `json:"loadprogramargs"`
	// Command arguments for LoadSystemFromFile command
	LoadSystemFromFileArgs *LoadSystemFromFileArgs `json:"loadsystemfromfileargs"`
	// Command arguments for LoadProgramFromFile command
	LoadProgramFromFileArgs *LoadProgramFromFileArgs `json:"loadprogramfromfileargs"`
	// Command arguments for LoadRuntime command
	LoadRuntimeArgs *LoadRuntimeArgs `json:"loadruntimeargs"`
	// Command arguments for Load command
	LoadArgs *LoadArgs `json:"loadargs"`
}

// Code generated by codegen; DO NOT EDIT.

// DebuggerCommandResult represents the result of a debugger command
type DebuggerCommandResult struct {
	// Unique ID for this command instance
	Id uint64 `json:"id"`
	// Command identifier
	Command DebuggerCommandId `json:"command"`
	// Result of Step command
	StepResult *ExecutionResult `json:"stepresult"`
	// Result of Continue command
	ContinueResult *ExecutionResult `json:"continueresult"`
	// Result of Run command
	RunResult *ExecutionResult `json:"runresult"`
	// Result of Interrupt command
	InterruptResult *ExecutionResult `json:"interruptresult"`
	// Result of Break command
	BreakResult *BreakResult `json:"breakresult"`
	// Result of Watch command
	WatchResult *WatchResult `json:"watchresult"`
	// Result of RemoveBreakpoint command
	RemoveBreakpointResult *RemoveBreakpointResult `json:"removebreakpointresult"`
	// Result of RemoveWatchpoint command
	RemoveWatchpointResult *RemoveWatchpointResult `json:"removewatchpointresult"`
	// Result of List command
	ListResult *ListResult `json:"listresult"`
	// Result of Disasm command
	DisasmResult *DisasmResult `json:"disasmresult"`
	// Result of CurrentInstruction command
	CurrentInstructionResult *CurrentInstructionResult `json:"currentinstructionresult"`
	// Result of Memory command
	MemoryResult *MemoryResult `json:"memoryresult"`
	// Result of Source command
	SourceResult *SourceResult `json:"sourceresult"`
	// Result of CurrentSource command
	CurrentSourceResult *SourceResult `json:"currentsourceresult"`
	// Result of Eval command
	EvalResult *EvalResult `json:"evalresult"`
	// Result of Info command
	InfoResult *InfoResult `json:"inforesult"`
	// Result of Registers command
	RegistersResult *RegistersResult `json:"registersresult"`
	// Result of Stack command
	StackResult *StackResult `json:"stackresult"`
	// Result of Vars command
	VarsResult *VarsResult `json:"varsresult"`
	// Result of Symbols command
	SymbolsResult *SymbolsResult `json:"symbolsresult"`
	// Result of Reset command
	ResetResult *ExecutionResult `json:"resetresult"`
	// Result of Restart command
	RestartResult *ExecutionResult `json:"restartresult"`
	// Result of LoadSystem command
	LoadSystemResult *LoadSystemFromEmbeddedResult `json:"loadsystemresult"`
	// Result of LoadProgram command
	LoadProgramResult *LoadProgramFromFileResult `json:"loadprogramresult"`
	// Result of LoadSystemFromFile command
	LoadSystemFromFileResult *LoadSystemFromFileResult `json:"loadsystemfromfileresult"`
	// Result of LoadSystemFromEmbedded command
	LoadSystemFromEmbeddedResult *LoadSystemFromEmbeddedResult `json:"loadsystemfromembeddedresult"`
	// Result of LoadProgramFromFile command
	LoadProgramFromFileResult *LoadProgramFromFileResult `json:"loadprogramfromfileresult"`
	// Result of LoadRuntime command
	LoadRuntimeResult *LoadRuntimeResult `json:"loadruntimeresult"`
	// Result of Load command
	LoadResult *LoadResult `json:"loadresult"`
}

func (c *commandBasedDebuggerAdapter) Execute(cmd *DebuggerCommand) (result *DebuggerCommandResult, err error) {

	switch cmd.Command {
	case DebuggerCommandStep:
		callResult := c.debugger.Step(cmd.StepArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			StepResult: callResult,
		}
	case DebuggerCommandContinue:
		callResult := c.debugger.Continue()
		result = &DebuggerCommandResult{
			Id:             cmd.Id,
			Command:        cmd.Command,
			ContinueResult: callResult,
		}
	case DebuggerCommandRun:
		callResult := c.debugger.Run()
		result = &DebuggerCommandResult{
			Id:        cmd.Id,
			Command:   cmd.Command,
			RunResult: callResult,
		}
	case DebuggerCommandInterrupt:
		callResult := c.debugger.Interrupt()
		result = &DebuggerCommandResult{
			Id:              cmd.Id,
			Command:         cmd.Command,
			InterruptResult: callResult,
		}
	case DebuggerCommandBreak:
		callResult := c.debugger.Break(cmd.BreakArgs)
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			BreakResult: callResult,
		}
	case DebuggerCommandWatch:
		callResult := c.debugger.Watch(cmd.WatchArgs)
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			WatchResult: callResult,
		}
	case DebuggerCommandRemoveBreakpoint:
		callResult := c.debugger.RemoveBreakpoint(cmd.RemoveBreakpointArgs)
		result = &DebuggerCommandResult{
			Id:                     cmd.Id,
			Command:                cmd.Command,
			RemoveBreakpointResult: callResult,
		}
	case DebuggerCommandRemoveWatchpoint:
		callResult := c.debugger.RemoveWatchpoint(cmd.RemoveWatchpointArgs)
		result = &DebuggerCommandResult{
			Id:                     cmd.Id,
			Command:                cmd.Command,
			RemoveWatchpointResult: callResult,
		}
	case DebuggerCommandList:
		callResult := c.debugger.List()
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			ListResult: callResult,
		}
	case DebuggerCommandDisasm:
		callResult := c.debugger.Disasm(cmd.DisasmArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			DisasmResult: callResult,
		}
	case DebuggerCommandCurrentInstruction:
		callResult := c.debugger.CurrentInstruction()
		result = &DebuggerCommandResult{
			Id:                       cmd.Id,
			Command:                  cmd.Command,
			CurrentInstructionResult: callResult,
		}
	case DebuggerCommandMemory:
		callResult := c.debugger.Memory(cmd.MemoryArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			MemoryResult: callResult,
		}
	case DebuggerCommandSource:
		callResult := c.debugger.Source(cmd.SourceArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			SourceResult: callResult,
		}
	case DebuggerCommandCurrentSource:
		callResult := c.debugger.CurrentSource(cmd.CurrentSourceArgs)
		result = &DebuggerCommandResult{
			Id:                  cmd.Id,
			Command:             cmd.Command,
			CurrentSourceResult: callResult,
		}
	case DebuggerCommandEval:
		callResult := c.debugger.Eval(cmd.EvalArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			EvalResult: callResult,
		}
	case DebuggerCommandInfo:
		callResult := c.debugger.Info(cmd.InfoArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			InfoResult: callResult,
		}
	case DebuggerCommandRegisters:
		callResult := c.debugger.Registers()
		result = &DebuggerCommandResult{
			Id:              cmd.Id,
			Command:         cmd.Command,
			RegistersResult: callResult,
		}
	case DebuggerCommandStack:
		callResult := c.debugger.Stack()
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			StackResult: callResult,
		}
	case DebuggerCommandVars:
		callResult := c.debugger.Vars()
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			VarsResult: callResult,
		}
	case DebuggerCommandSymbols:
		callResult := c.debugger.Symbols(cmd.SymbolsArgs)
		result = &DebuggerCommandResult{
			Id:            cmd.Id,
			Command:       cmd.Command,
			SymbolsResult: callResult,
		}
	case DebuggerCommandReset:
		callResult := c.debugger.Reset()
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			ResetResult: callResult,
		}
	case DebuggerCommandRestart:
		callResult := c.debugger.Restart()
		result = &DebuggerCommandResult{
			Id:            cmd.Id,
			Command:       cmd.Command,
			RestartResult: callResult,
		}
	case DebuggerCommandLoadSystem:
		callResult := c.debugger.LoadSystem(cmd.LoadSystemArgs)
		result = &DebuggerCommandResult{
			Id:               cmd.Id,
			Command:          cmd.Command,
			LoadSystemResult: callResult,
		}
	case DebuggerCommandLoadProgram:
		callResult := c.debugger.LoadProgram(cmd.LoadProgramArgs)
		result = &DebuggerCommandResult{
			Id:                cmd.Id,
			Command:           cmd.Command,
			LoadProgramResult: callResult,
		}
	case DebuggerCommandLoadSystemFromFile:
		callResult := c.debugger.LoadSystemFromFile(cmd.LoadSystemFromFileArgs)
		result = &DebuggerCommandResult{
			Id:                       cmd.Id,
			Command:                  cmd.Command,
			LoadSystemFromFileResult: callResult,
		}
	case DebuggerCommandLoadSystemFromEmbedded:
		callResult := c.debugger.LoadSystemFromEmbedded()
		result = &DebuggerCommandResult{
			Id:                           cmd.Id,
			Command:                      cmd.Command,
			LoadSystemFromEmbeddedResult: callResult,
		}
	case DebuggerCommandLoadProgramFromFile:
		callResult := c.debugger.LoadProgramFromFile(cmd.LoadProgramFromFileArgs)
		result = &DebuggerCommandResult{
			Id:                        cmd.Id,
			Command:                   cmd.Command,
			LoadProgramFromFileResult: callResult,
		}
	case DebuggerCommandLoadRuntime:
		callResult := c.debugger.LoadRuntime(cmd.LoadRuntimeArgs)
		result = &DebuggerCommandResult{
			Id:                cmd.Id,
			Command:           cmd.Command,
			LoadRuntimeResult: callResult,
		}
	case DebuggerCommandLoad:
		callResult := c.debugger.Load(cmd.LoadArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			LoadResult: callResult,
		}
	default:
		err = fmt.Errorf("unknown command ID: %d", cmd.Command)
	}

	return
}

// CommandsDocumentation contains the complete documentation for all debugger commands
var CommandsDocumentation Documentation = Documentation(Documentation(map[DebuggerCommandId]*CommandDocumentation{
	DebuggerCommandId(DebuggerCommandId(1)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(1)),
		CommandName:  "continue",
		MethodName:   "Continue",
		Summary:      "Continues execution until the next breakpoint/watchpoint/termination\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(12)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(12)),
		CommandName:  "source",
		MethodName:   "Source",
		Summary:      "Displays source code\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"ContextLines": &ArgumentDocumentation{
				FieldName:    "ContextLines",
				TypeName:     "int",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ContextMode": &ArgumentDocumentation{
				FieldName:    "ContextMode",
				TypeName:     "SourceContextMode",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Location": &ArgumentDocumentation{
				FieldName:    "Location",
				TypeName:     "*SourceLocation",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Snippet": &ArgumentDocumentation{
				FieldName:    "Snippet",
				TypeName:     "*SourceCodeSnippet",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(18)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(18)),
		CommandName:  "vars",
		MethodName:   "Vars",
		Summary:      "Returns accessible variables\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Variables": &ArgumentDocumentation{
				FieldName:    "Variables",
				TypeName:     "[]*VariableValue",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(27)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(27)),
		CommandName:  "loadRuntime",
		MethodName:   "LoadRuntime",
		Summary:      "Configure the execution runtime used to run the debugged program\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"Runtime": &ArgumentDocumentation{
				FieldName:    "Runtime",
				TypeName:     "RuntimeType",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Runtime": &ArgumentDocumentation{
				FieldName:    "Runtime",
				TypeName:     "*RuntimeInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(10)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(10)),
		CommandName:  "currentInstruction",
		MethodName:   "CurrentInstruction",
		Summary:      "Returns the current instruction for display\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Instruction": &ArgumentDocumentation{
				FieldName:    "Instruction",
				TypeName:     "*Instruction",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(11)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(11)),
		CommandName:  "memory",
		MethodName:   "Memory",
		Summary:      "Displays memory. Args: address expression, optional count\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"AddressExpr": &ArgumentDocumentation{
				FieldName:    "AddressExpr",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"CountExpr": &ArgumentDocumentation{
				FieldName:    "CountExpr",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Address": &ArgumentDocumentation{
				FieldName:    "Address",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Data": &ArgumentDocumentation{
				FieldName:    "Data",
				TypeName:     "[]byte",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Regions": &ArgumentDocumentation{
				FieldName:    "Regions",
				TypeName:     "[]*MemoryRegion",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(14)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(14)),
		CommandName:  "eval",
		MethodName:   "Eval",
		Summary:      "Evaluates an expression\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"Expression": &ArgumentDocumentation{
				FieldName:    "Expression",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Value": &ArgumentDocumentation{
				FieldName:    "Value",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ValueBytes": &ArgumentDocumentation{
				FieldName:    "ValueBytes",
				TypeName:     "[]byte",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ValueString": &ArgumentDocumentation{
				FieldName:    "ValueString",
				TypeName:     "string",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(17)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(17)),
		CommandName:  "stack",
		MethodName:   "Stack",
		Summary:      "Returns stack information\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"SP": &ArgumentDocumentation{
				FieldName:    "SP",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StackData": &ArgumentDocumentation{
				FieldName:    "StackData",
				TypeName:     "[]byte",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StackFrames": &ArgumentDocumentation{
				FieldName:    "StackFrames",
				TypeName:     "[]*StackFrame",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(21)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(21)),
		CommandName:  "restart",
		MethodName:   "Restart",
		Summary:      "Restarts the program (reset + continue)\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(26)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(26)),
		CommandName:  "loadProgramFromFile",
		MethodName:   "LoadProgramFromFile",
		Summary:      "Load a program into the debugged runtime from a file (full method name).\n\nNote that this may involve compiling the input file. Any error or warning during\ncompilation or loading will be returned.\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"AutoBuildClang": &ArgumentDocumentation{
				FieldName:    "AutoBuildClang",
				TypeName:     "*bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"FilePath": &ArgumentDocumentation{
				FieldName:    "FilePath",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ForceRebuildClang": &ArgumentDocumentation{
				FieldName:    "ForceRebuildClang",
				TypeName:     "*bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Program": &ArgumentDocumentation{
				FieldName:    "Program",
				TypeName:     "*ProgramInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(5)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(5)),
		CommandName:  "watch",
		MethodName:   "Watch",
		Summary:      "Adds a watchpoint. Args: address or symbol\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"EndAddress": &ArgumentDocumentation{
				FieldName:    "EndAddress",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Size": &ArgumentDocumentation{
				FieldName:    "Size",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StartAddress": &ArgumentDocumentation{
				FieldName:    "StartAddress",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Type": &ArgumentDocumentation{
				FieldName:    "Type",
				TypeName:     "*WatchpointType",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(9)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(9)),
		CommandName:  "disasm",
		MethodName:   "Disasm",
		Summary:      "Disassembles instructions. Args: optional address, optional count\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"Address": &ArgumentDocumentation{
				FieldName:    "Address",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"CountExpr": &ArgumentDocumentation{
				FieldName:    "CountExpr",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ShowCFG": &ArgumentDocumentation{
				FieldName:    "ShowCFG",
				TypeName:     "bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ShowSource": &ArgumentDocumentation{
				FieldName:    "ShowSource",
				TypeName:     "bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"ControlFlowGraph": &ArgumentDocumentation{
				FieldName:    "ControlFlowGraph",
				TypeName:     "*ControlFlowGraph",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Instructions": &ArgumentDocumentation{
				FieldName:    "Instructions",
				TypeName:     "[]*Instruction",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(22)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(22)),
		CommandName:  "loadSystem",
		MethodName:   "LoadSystem",
		Summary:      "Load system configuration - uses embedded default\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"System": &ArgumentDocumentation{
				FieldName:    "System",
				TypeName:     "*SystemInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(25)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(25)),
		CommandName:  "loadSystemFromEmbedded",
		MethodName:   "LoadSystemFromEmbedded",
		Summary:      "Load the embedded default system configuration\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"System": &ArgumentDocumentation{
				FieldName:    "System",
				TypeName:     "*SystemInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(28)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(28)),
		CommandName:  "load",
		MethodName:   "Load",
		Summary:      "Loads program, system, and runtime from a single YAML file\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"FullDescriptorPath": &ArgumentDocumentation{
				FieldName:    "FullDescriptorPath",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ProgramPath": &ArgumentDocumentation{
				FieldName:    "ProgramPath",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Runtime": &ArgumentDocumentation{
				FieldName:    "Runtime",
				TypeName:     "*RuntimeType",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"SystemConfigPath": &ArgumentDocumentation{
				FieldName:    "SystemConfigPath",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Program": &ArgumentDocumentation{
				FieldName:    "Program",
				TypeName:     "*LoadProgramFromFileResult",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Runtime": &ArgumentDocumentation{
				FieldName:    "Runtime",
				TypeName:     "*LoadRuntimeResult",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"System": &ArgumentDocumentation{
				FieldName:    "System",
				TypeName:     "*LoadSystemFromFileResult",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(3)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(3)),
		CommandName:  "interrupt",
		MethodName:   "Interrupt",
		Summary:      "Interrupts execution\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(4)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(4)),
		CommandName:  "break",
		MethodName:   "Break",
		Summary:      "Adds a breakpoint. Args: address or symbol\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"Address": &ArgumentDocumentation{
				FieldName:    "Address",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"SourceLocation": &ArgumentDocumentation{
				FieldName:    "SourceLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(8)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(8)),
		CommandName:  "list",
		MethodName:   "List",
		Summary:      "Returns breakpoints and watchpoints\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoints": &ArgumentDocumentation{
				FieldName:    "Breakpoints",
				TypeName:     "[]*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoints": &ArgumentDocumentation{
				FieldName:    "Watchpoints",
				TypeName:     "[]*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(15)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(15)),
		CommandName:  "info",
		MethodName:   "Info",
		Summary:      "Returns current debugger state, system info, or program info\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"Type": &ArgumentDocumentation{
				FieldName:    "Type",
				TypeName:     "InfoType",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"DebuggerState": &ArgumentDocumentation{
				FieldName:    "DebuggerState",
				TypeName:     "*DebuggerState",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ProgramInfo": &ArgumentDocumentation{
				FieldName:    "ProgramInfo",
				TypeName:     "*ProgramInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"RuntimeInfo": &ArgumentDocumentation{
				FieldName:    "RuntimeInfo",
				TypeName:     "*RuntimeInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"SystemInfo": &ArgumentDocumentation{
				FieldName:    "SystemInfo",
				TypeName:     "*SystemInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(0)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(0)),
		CommandName:  "step",
		MethodName:   "Step",
		Summary:      "Executes a single execution step\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"CountMode": &ArgumentDocumentation{
				FieldName:    "CountMode",
				TypeName:     "StepCountMode",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StepMode": &ArgumentDocumentation{
				FieldName:    "StepMode",
				TypeName:     "StepMode",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(16)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(16)),
		CommandName:  "registers",
		MethodName:   "Registers",
		Summary:      "Returns all register values\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Flags": &ArgumentDocumentation{
				FieldName:    "Flags",
				TypeName:     "*FlagState",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Registers": &ArgumentDocumentation{
				FieldName:    "Registers",
				TypeName:     "map[string]*Register",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(2)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(2)),
		CommandName:  "run",
		MethodName:   "Run",
		Summary:      "CmdRun executes run command\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(23)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(23)),
		CommandName:  "loadProgram",
		MethodName:   "LoadProgram",
		Summary:      "Load a program into the debugged runtime from a file.\n\nNote that this may involve compiling the input file. Any error or warning during\ncompilation or loading will be returned.\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"AutoBuildClang": &ArgumentDocumentation{
				FieldName:    "AutoBuildClang",
				TypeName:     "*bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"FilePath": &ArgumentDocumentation{
				FieldName:    "FilePath",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ForceRebuildClang": &ArgumentDocumentation{
				FieldName:    "ForceRebuildClang",
				TypeName:     "*bool",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Program": &ArgumentDocumentation{
				FieldName:    "Program",
				TypeName:     "*ProgramInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(20)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(20)),
		CommandName:  "reset",
		MethodName:   "Reset",
		Summary:      "Resets the program to its initial state\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments:    map[string]*ArgumentDocumentation{},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Cycles": &ArgumentDocumentation{
				FieldName:    "Cycles",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LaggingCycles": &ArgumentDocumentation{
				FieldName:    "LaggingCycles",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastInstruction": &ArgumentDocumentation{
				FieldName:    "LastInstruction",
				TypeName:     "uint32",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"LastLocation": &ArgumentDocumentation{
				FieldName:    "LastLocation",
				TypeName:     "*SourceLocation",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Steps": &ArgumentDocumentation{
				FieldName:    "Steps",
				TypeName:     "uint64",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"StopReason": &ArgumentDocumentation{
				FieldName:    "StopReason",
				TypeName:     "StopReason",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(6)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(6)),
		CommandName:  "removeBreakpoint",
		MethodName:   "RemoveBreakpoint",
		Summary:      "Deletes a breakpoint or watchpoint. Args: id\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"ID": &ArgumentDocumentation{
				FieldName:    "ID",
				TypeName:     "int",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Breakpoint": &ArgumentDocumentation{
				FieldName:    "Breakpoint",
				TypeName:     "*Breakpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(7)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(7)),
		CommandName:  "removeWatchpoint",
		MethodName:   "RemoveWatchpoint",
		Summary:      "Deletes a watchpoint. Args: id\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"ID": &ArgumentDocumentation{
				FieldName:    "ID",
				TypeName:     "int",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Watchpoint": &ArgumentDocumentation{
				FieldName:    "Watchpoint",
				TypeName:     "*Watchpoint",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(13)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(13)),
		CommandName:  "currentSource",
		MethodName:   "CurrentSource",
		Summary:      "Displays the current source\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"ContextLines": &ArgumentDocumentation{
				FieldName:    "ContextLines",
				TypeName:     "int",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"ContextMode": &ArgumentDocumentation{
				FieldName:    "ContextMode",
				TypeName:     "SourceContextMode",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Snippet": &ArgumentDocumentation{
				FieldName:    "Snippet",
				TypeName:     "*SourceCodeSnippet",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(19)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(19)),
		CommandName:  "symbols",
		MethodName:   "Symbols",
		Summary:      "Returns symbols from the loaded program\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"SymbolName": &ArgumentDocumentation{
				FieldName:    "SymbolName",
				TypeName:     "*string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Functions": &ArgumentDocumentation{
				FieldName:    "Functions",
				TypeName:     "[]*FunctionSymbol",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Globals": &ArgumentDocumentation{
				FieldName:    "Globals",
				TypeName:     "[]*GlobalSymbol",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"Labels": &ArgumentDocumentation{
				FieldName:    "Labels",
				TypeName:     "[]*LabelSymbol",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"TotalCount": &ArgumentDocumentation{
				FieldName:    "TotalCount",
				TypeName:     "int",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
	DebuggerCommandId(DebuggerCommandId(24)): &CommandDocumentation{
		CommandID:    DebuggerCommandId(DebuggerCommandId(24)),
		CommandName:  "loadSystemFromFile",
		MethodName:   "LoadSystemFromFile",
		Summary:      "Load system configuration from a YAML file\n",
		Description:  "",
		Placeholders: []*DocumentationPlaceholder{},
		Arguments: map[string]*ArgumentDocumentation{
			"FilePath": &ArgumentDocumentation{
				FieldName:    "FilePath",
				TypeName:     "string",
				IsRequired:   true,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Results: map[string]*ArgumentDocumentation{
			"Error": &ArgumentDocumentation{
				FieldName:    "Error",
				TypeName:     "error",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
			"System": &ArgumentDocumentation{
				FieldName:    "System",
				TypeName:     "*SystemInfo",
				IsRequired:   false,
				Summary:      "",
				Description:  "",
				Placeholders: []*DocumentationPlaceholder{},
				EnumValues:   map[string]string{},
			},
		},
		Examples: []CommandExample{},
	},
})) // Code generated by codegen; DO NOT EDIT.

// DebuggerCommandId is an enum of all supported debugger commands
type DebuggerCommandId int

const (
	// Executes a single execution step
	DebuggerCommandStep DebuggerCommandId = DebuggerCommandId(0)
	// Continues execution until the next breakpoint/watchpoint/termination
	DebuggerCommandContinue DebuggerCommandId = DebuggerCommandId(1)
	// CmdRun executes run command
	DebuggerCommandRun DebuggerCommandId = DebuggerCommandId(2)
	// Interrupts execution
	DebuggerCommandInterrupt DebuggerCommandId = DebuggerCommandId(3)
	// Adds a breakpoint. Args: address or symbol
	DebuggerCommandBreak DebuggerCommandId = DebuggerCommandId(4)
	// Adds a watchpoint. Args: address or symbol
	DebuggerCommandWatch DebuggerCommandId = DebuggerCommandId(5)
	// Deletes a breakpoint or watchpoint. Args: id
	DebuggerCommandRemoveBreakpoint DebuggerCommandId = DebuggerCommandId(6)
	// Deletes a watchpoint. Args: id
	DebuggerCommandRemoveWatchpoint DebuggerCommandId = DebuggerCommandId(7)
	// Returns breakpoints and watchpoints
	DebuggerCommandList DebuggerCommandId = DebuggerCommandId(8)
	// Disassembles instructions. Args: optional address, optional count
	DebuggerCommandDisasm DebuggerCommandId = DebuggerCommandId(9)
	// Returns the current instruction for display
	DebuggerCommandCurrentInstruction DebuggerCommandId = DebuggerCommandId(10)
	// Displays memory. Args: address expression, optional count
	DebuggerCommandMemory DebuggerCommandId = DebuggerCommandId(11)
	// Displays source code
	DebuggerCommandSource DebuggerCommandId = DebuggerCommandId(12)
	// Displays the current source
	DebuggerCommandCurrentSource DebuggerCommandId = DebuggerCommandId(13)
	// Evaluates an expression
	DebuggerCommandEval DebuggerCommandId = DebuggerCommandId(14)
	// Returns current debugger state, system info, or program info
	DebuggerCommandInfo DebuggerCommandId = DebuggerCommandId(15)
	// Returns all register values
	DebuggerCommandRegisters DebuggerCommandId = DebuggerCommandId(16)
	// Returns stack information
	DebuggerCommandStack DebuggerCommandId = DebuggerCommandId(17)
	// Returns accessible variables
	DebuggerCommandVars DebuggerCommandId = DebuggerCommandId(18)
	// Returns symbols from the loaded program
	DebuggerCommandSymbols DebuggerCommandId = DebuggerCommandId(19)
	// Resets the program to its initial state
	DebuggerCommandReset DebuggerCommandId = DebuggerCommandId(20)
	// Restarts the program (reset + continue)
	DebuggerCommandRestart DebuggerCommandId = DebuggerCommandId(21)
	// Load system configuration - uses embedded default
	DebuggerCommandLoadSystem DebuggerCommandId = DebuggerCommandId(22)
	// Load a program into the debugged runtime from a file.
	//
	// Note that this may involve compiling the input file. Any error or warning during
	// compilation or loading will be returned.
	DebuggerCommandLoadProgram DebuggerCommandId = DebuggerCommandId(23)
	// Load system configuration from a YAML file
	DebuggerCommandLoadSystemFromFile DebuggerCommandId = DebuggerCommandId(24)
	// Load the embedded default system configuration
	DebuggerCommandLoadSystemFromEmbedded DebuggerCommandId = DebuggerCommandId(25)
	// Load a program into the debugged runtime from a file (full method name).
	//
	// Note that this may involve compiling the input file. Any error or warning during
	// compilation or loading will be returned.
	DebuggerCommandLoadProgramFromFile DebuggerCommandId = DebuggerCommandId(26)
	// Configure the execution runtime used to run the debugged program
	DebuggerCommandLoadRuntime DebuggerCommandId = DebuggerCommandId(27)
	// Loads program, system, and runtime from a single YAML file
	DebuggerCommandLoad DebuggerCommandId = DebuggerCommandId(28)
)

func (e DebuggerCommandId) String() string {

	switch e {
	case DebuggerCommandStep:
		return "DebuggerCommandStep"
	case DebuggerCommandContinue:
		return "DebuggerCommandContinue"
	case DebuggerCommandRun:
		return "DebuggerCommandRun"
	case DebuggerCommandInterrupt:
		return "DebuggerCommandInterrupt"
	case DebuggerCommandBreak:
		return "DebuggerCommandBreak"
	case DebuggerCommandWatch:
		return "DebuggerCommandWatch"
	case DebuggerCommandRemoveBreakpoint:
		return "DebuggerCommandRemoveBreakpoint"
	case DebuggerCommandRemoveWatchpoint:
		return "DebuggerCommandRemoveWatchpoint"
	case DebuggerCommandList:
		return "DebuggerCommandList"
	case DebuggerCommandDisasm:
		return "DebuggerCommandDisasm"
	case DebuggerCommandCurrentInstruction:
		return "DebuggerCommandCurrentInstruction"
	case DebuggerCommandMemory:
		return "DebuggerCommandMemory"
	case DebuggerCommandSource:
		return "DebuggerCommandSource"
	case DebuggerCommandCurrentSource:
		return "DebuggerCommandCurrentSource"
	case DebuggerCommandEval:
		return "DebuggerCommandEval"
	case DebuggerCommandInfo:
		return "DebuggerCommandInfo"
	case DebuggerCommandRegisters:
		return "DebuggerCommandRegisters"
	case DebuggerCommandStack:
		return "DebuggerCommandStack"
	case DebuggerCommandVars:
		return "DebuggerCommandVars"
	case DebuggerCommandSymbols:
		return "DebuggerCommandSymbols"
	case DebuggerCommandReset:
		return "DebuggerCommandReset"
	case DebuggerCommandRestart:
		return "DebuggerCommandRestart"
	case DebuggerCommandLoadSystem:
		return "DebuggerCommandLoadSystem"
	case DebuggerCommandLoadProgram:
		return "DebuggerCommandLoadProgram"
	case DebuggerCommandLoadSystemFromFile:
		return "DebuggerCommandLoadSystemFromFile"
	case DebuggerCommandLoadSystemFromEmbedded:
		return "DebuggerCommandLoadSystemFromEmbedded"
	case DebuggerCommandLoadProgramFromFile:
		return "DebuggerCommandLoadProgramFromFile"
	case DebuggerCommandLoadRuntime:
		return "DebuggerCommandLoadRuntime"
	case DebuggerCommandLoad:
		return "DebuggerCommandLoad"
	default:
		return "unknown"
	}
}
func DebuggerCommandIdFromString(s string) (DebuggerCommandId, error) {

	switch s {
	case "DebuggerCommandStep":
		return DebuggerCommandStep, nil
	case "DebuggerCommandContinue":
		return DebuggerCommandContinue, nil
	case "DebuggerCommandRun":
		return DebuggerCommandRun, nil
	case "DebuggerCommandInterrupt":
		return DebuggerCommandInterrupt, nil
	case "DebuggerCommandBreak":
		return DebuggerCommandBreak, nil
	case "DebuggerCommandWatch":
		return DebuggerCommandWatch, nil
	case "DebuggerCommandRemoveBreakpoint":
		return DebuggerCommandRemoveBreakpoint, nil
	case "DebuggerCommandRemoveWatchpoint":
		return DebuggerCommandRemoveWatchpoint, nil
	case "DebuggerCommandList":
		return DebuggerCommandList, nil
	case "DebuggerCommandDisasm":
		return DebuggerCommandDisasm, nil
	case "DebuggerCommandCurrentInstruction":
		return DebuggerCommandCurrentInstruction, nil
	case "DebuggerCommandMemory":
		return DebuggerCommandMemory, nil
	case "DebuggerCommandSource":
		return DebuggerCommandSource, nil
	case "DebuggerCommandCurrentSource":
		return DebuggerCommandCurrentSource, nil
	case "DebuggerCommandEval":
		return DebuggerCommandEval, nil
	case "DebuggerCommandInfo":
		return DebuggerCommandInfo, nil
	case "DebuggerCommandRegisters":
		return DebuggerCommandRegisters, nil
	case "DebuggerCommandStack":
		return DebuggerCommandStack, nil
	case "DebuggerCommandVars":
		return DebuggerCommandVars, nil
	case "DebuggerCommandSymbols":
		return DebuggerCommandSymbols, nil
	case "DebuggerCommandReset":
		return DebuggerCommandReset, nil
	case "DebuggerCommandRestart":
		return DebuggerCommandRestart, nil
	case "DebuggerCommandLoadSystem":
		return DebuggerCommandLoadSystem, nil
	case "DebuggerCommandLoadProgram":
		return DebuggerCommandLoadProgram, nil
	case "DebuggerCommandLoadSystemFromFile":
		return DebuggerCommandLoadSystemFromFile, nil
	case "DebuggerCommandLoadSystemFromEmbedded":
		return DebuggerCommandLoadSystemFromEmbedded, nil
	case "DebuggerCommandLoadProgramFromFile":
		return DebuggerCommandLoadProgramFromFile, nil
	case "DebuggerCommandLoadRuntime":
		return DebuggerCommandLoadRuntime, nil
	case "DebuggerCommandLoad":
		return DebuggerCommandLoad, nil
	default:
		return 0, fmt.Errorf("unknown %s: %s", "DebuggerCommandId", s)
	}
}
func (e DebuggerCommandId) MarshalJSON() ([]byte, error) {

	return json.Marshal(e.String())
}
func (e *DebuggerCommandId) UnmarshalJSON(data []byte) error {

	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := DebuggerCommandIdFromString(str)
	if err != nil {
		return err
	}
	*e = val

	return nil
}

// A map of all DebuggerCommandId values for easy lookup
var DebuggerCommandIdValues map[DebuggerCommandId]bool = map[DebuggerCommandId]bool{
	DebuggerCommandStep:                   true,
	DebuggerCommandContinue:               true,
	DebuggerCommandRun:                    true,
	DebuggerCommandInterrupt:              true,
	DebuggerCommandBreak:                  true,
	DebuggerCommandWatch:                  true,
	DebuggerCommandRemoveBreakpoint:       true,
	DebuggerCommandRemoveWatchpoint:       true,
	DebuggerCommandList:                   true,
	DebuggerCommandDisasm:                 true,
	DebuggerCommandCurrentInstruction:     true,
	DebuggerCommandMemory:                 true,
	DebuggerCommandSource:                 true,
	DebuggerCommandCurrentSource:          true,
	DebuggerCommandEval:                   true,
	DebuggerCommandInfo:                   true,
	DebuggerCommandRegisters:              true,
	DebuggerCommandStack:                  true,
	DebuggerCommandVars:                   true,
	DebuggerCommandSymbols:                true,
	DebuggerCommandReset:                  true,
	DebuggerCommandRestart:                true,
	DebuggerCommandLoadSystem:             true,
	DebuggerCommandLoadProgram:            true,
	DebuggerCommandLoadSystemFromFile:     true,
	DebuggerCommandLoadSystemFromEmbedded: true,
	DebuggerCommandLoadProgramFromFile:    true,
	DebuggerCommandLoadRuntime:            true,
	DebuggerCommandLoad:                   true,
}
