// Code generated by codegen; DO NOT EDIT.

package debugger

import (
	"encoding/json"
	"fmt"
)

// Code generated by codegen; DO NOT EDIT.

// DebuggerCommand represents a debugger command with its arguments
type DebuggerCommand struct {
	// Unique ID for this command instance
	Id uint64 `json:"id"`
	// Type of command
	Command DebuggerCommandId `json:"command"`
	// Command arguments for Step command
	StepArgs *StepArgs `json:"stepargs"`
	// Command arguments for Break command
	BreakArgs *BreakArgs `json:"breakargs"`
	// Command arguments for Watch command
	WatchArgs *WatchArgs `json:"watchargs"`
	// Command arguments for RemoveBreakpoint command
	RemoveBreakpointArgs *RemoveBreakpointArgs `json:"removebreakpointargs"`
	// Command arguments for RemoveWatchpoint command
	RemoveWatchpointArgs *RemoveWatchpointArgs `json:"removewatchpointargs"`
	// Command arguments for Disasm command
	DisasmArgs *DisasmArgs `json:"disasmargs"`
	// Command arguments for Memory command
	MemoryArgs *MemoryArgs `json:"memoryargs"`
	// Command arguments for Source command
	SourceArgs *SourceArgs `json:"sourceargs"`
	// Command arguments for CurrentSource command
	CurrentSourceArgs *CurrentSourceArgs `json:"currentsourceargs"`
	// Command arguments for Eval command
	EvalArgs *EvalArgs `json:"evalargs"`
	// Command arguments for Info command
	InfoArgs *InfoArgs `json:"infoargs"`
	// Command arguments for Symbols command
	SymbolsArgs *SymbolsArgs `json:"symbolsargs"`
	// Command arguments for LoadSystem command
	LoadSystemArgs *LoadSystemArgs `json:"loadsystemargs"`
	// Command arguments for LoadProgram command
	LoadProgramArgs *LoadProgramArgs `json:"loadprogramargs"`
	// Command arguments for LoadSystemFromFile command
	LoadSystemFromFileArgs *LoadSystemFromFileArgs `json:"loadsystemfromfileargs"`
	// Command arguments for LoadProgramFromFile command
	LoadProgramFromFileArgs *LoadProgramFromFileArgs `json:"loadprogramfromfileargs"`
	// Command arguments for LoadRuntime command
	LoadRuntimeArgs *LoadRuntimeArgs `json:"loadruntimeargs"`
	// Command arguments for Load command
	LoadArgs *LoadArgs `json:"loadargs"`
}

// Code generated by codegen; DO NOT EDIT.

// DebuggerCommandResult represents the result of a debugger command
type DebuggerCommandResult struct {
	// Unique ID for this command instance
	Id uint64 `json:"id"`
	// Command identifier
	Command DebuggerCommandId `json:"command"`
	// Result of Step command
	StepResult *ExecutionResult `json:"stepresult"`
	// Result of Continue command
	ContinueResult *ExecutionResult `json:"continueresult"`
	// Result of Run command
	RunResult *ExecutionResult `json:"runresult"`
	// Result of Interrupt command
	InterruptResult *ExecutionResult `json:"interruptresult"`
	// Result of Break command
	BreakResult *BreakResult `json:"breakresult"`
	// Result of Watch command
	WatchResult *WatchResult `json:"watchresult"`
	// Result of RemoveBreakpoint command
	RemoveBreakpointResult *RemoveBreakpointResult `json:"removebreakpointresult"`
	// Result of RemoveWatchpoint command
	RemoveWatchpointResult *RemoveWatchpointResult `json:"removewatchpointresult"`
	// Result of List command
	ListResult *ListResult `json:"listresult"`
	// Result of Disasm command
	DisasmResult *DisasmResult `json:"disasmresult"`
	// Result of CurrentInstruction command
	CurrentInstructionResult *CurrentInstructionResult `json:"currentinstructionresult"`
	// Result of Memory command
	MemoryResult *MemoryResult `json:"memoryresult"`
	// Result of Source command
	SourceResult *SourceResult `json:"sourceresult"`
	// Result of CurrentSource command
	CurrentSourceResult *SourceResult `json:"currentsourceresult"`
	// Result of Eval command
	EvalResult *EvalResult `json:"evalresult"`
	// Result of Info command
	InfoResult *InfoResult `json:"inforesult"`
	// Result of Registers command
	RegistersResult *RegistersResult `json:"registersresult"`
	// Result of Stack command
	StackResult *StackResult `json:"stackresult"`
	// Result of Vars command
	VarsResult *VarsResult `json:"varsresult"`
	// Result of Symbols command
	SymbolsResult *SymbolsResult `json:"symbolsresult"`
	// Result of Reset command
	ResetResult *ExecutionResult `json:"resetresult"`
	// Result of Restart command
	RestartResult *ExecutionResult `json:"restartresult"`
	// Result of LoadSystem command
	LoadSystemResult *LoadSystemFromEmbeddedResult `json:"loadsystemresult"`
	// Result of LoadProgram command
	LoadProgramResult *LoadProgramFromFileResult `json:"loadprogramresult"`
	// Result of LoadSystemFromFile command
	LoadSystemFromFileResult *LoadSystemFromFileResult `json:"loadsystemfromfileresult"`
	// Result of LoadSystemFromEmbedded command
	LoadSystemFromEmbeddedResult *LoadSystemFromEmbeddedResult `json:"loadsystemfromembeddedresult"`
	// Result of LoadProgramFromFile command
	LoadProgramFromFileResult *LoadProgramFromFileResult `json:"loadprogramfromfileresult"`
	// Result of LoadRuntime command
	LoadRuntimeResult *LoadRuntimeResult `json:"loadruntimeresult"`
	// Result of Load command
	LoadResult *LoadResult `json:"loadresult"`
}

func (c *commandBasedDebuggerAdapter) Execute(cmd *DebuggerCommand) (result *DebuggerCommandResult, err error) {

	switch cmd.Command {
	case DebuggerCommandStep:
		callResult := c.debugger.Step(cmd.StepArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			StepResult: callResult,
		}
	case DebuggerCommandContinue:
		callResult := c.debugger.Continue()
		result = &DebuggerCommandResult{
			Id:             cmd.Id,
			Command:        cmd.Command,
			ContinueResult: callResult,
		}
	case DebuggerCommandRun:
		callResult := c.debugger.Run()
		result = &DebuggerCommandResult{
			Id:        cmd.Id,
			Command:   cmd.Command,
			RunResult: callResult,
		}
	case DebuggerCommandInterrupt:
		callResult := c.debugger.Interrupt()
		result = &DebuggerCommandResult{
			Id:              cmd.Id,
			Command:         cmd.Command,
			InterruptResult: callResult,
		}
	case DebuggerCommandBreak:
		callResult := c.debugger.Break(cmd.BreakArgs)
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			BreakResult: callResult,
		}
	case DebuggerCommandWatch:
		callResult := c.debugger.Watch(cmd.WatchArgs)
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			WatchResult: callResult,
		}
	case DebuggerCommandRemoveBreakpoint:
		callResult := c.debugger.RemoveBreakpoint(cmd.RemoveBreakpointArgs)
		result = &DebuggerCommandResult{
			Id:                     cmd.Id,
			Command:                cmd.Command,
			RemoveBreakpointResult: callResult,
		}
	case DebuggerCommandRemoveWatchpoint:
		callResult := c.debugger.RemoveWatchpoint(cmd.RemoveWatchpointArgs)
		result = &DebuggerCommandResult{
			Id:                     cmd.Id,
			Command:                cmd.Command,
			RemoveWatchpointResult: callResult,
		}
	case DebuggerCommandList:
		callResult := c.debugger.List()
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			ListResult: callResult,
		}
	case DebuggerCommandDisasm:
		callResult := c.debugger.Disasm(cmd.DisasmArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			DisasmResult: callResult,
		}
	case DebuggerCommandCurrentInstruction:
		callResult := c.debugger.CurrentInstruction()
		result = &DebuggerCommandResult{
			Id:                       cmd.Id,
			Command:                  cmd.Command,
			CurrentInstructionResult: callResult,
		}
	case DebuggerCommandMemory:
		callResult := c.debugger.Memory(cmd.MemoryArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			MemoryResult: callResult,
		}
	case DebuggerCommandSource:
		callResult := c.debugger.Source(cmd.SourceArgs)
		result = &DebuggerCommandResult{
			Id:           cmd.Id,
			Command:      cmd.Command,
			SourceResult: callResult,
		}
	case DebuggerCommandCurrentSource:
		callResult := c.debugger.CurrentSource(cmd.CurrentSourceArgs)
		result = &DebuggerCommandResult{
			Id:                  cmd.Id,
			Command:             cmd.Command,
			CurrentSourceResult: callResult,
		}
	case DebuggerCommandEval:
		callResult := c.debugger.Eval(cmd.EvalArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			EvalResult: callResult,
		}
	case DebuggerCommandInfo:
		callResult := c.debugger.Info(cmd.InfoArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			InfoResult: callResult,
		}
	case DebuggerCommandRegisters:
		callResult := c.debugger.Registers()
		result = &DebuggerCommandResult{
			Id:              cmd.Id,
			Command:         cmd.Command,
			RegistersResult: callResult,
		}
	case DebuggerCommandStack:
		callResult := c.debugger.Stack()
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			StackResult: callResult,
		}
	case DebuggerCommandVars:
		callResult := c.debugger.Vars()
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			VarsResult: callResult,
		}
	case DebuggerCommandSymbols:
		callResult := c.debugger.Symbols(cmd.SymbolsArgs)
		result = &DebuggerCommandResult{
			Id:            cmd.Id,
			Command:       cmd.Command,
			SymbolsResult: callResult,
		}
	case DebuggerCommandReset:
		callResult := c.debugger.Reset()
		result = &DebuggerCommandResult{
			Id:          cmd.Id,
			Command:     cmd.Command,
			ResetResult: callResult,
		}
	case DebuggerCommandRestart:
		callResult := c.debugger.Restart()
		result = &DebuggerCommandResult{
			Id:            cmd.Id,
			Command:       cmd.Command,
			RestartResult: callResult,
		}
	case DebuggerCommandLoadSystem:
		callResult := c.debugger.LoadSystem(cmd.LoadSystemArgs)
		result = &DebuggerCommandResult{
			Id:               cmd.Id,
			Command:          cmd.Command,
			LoadSystemResult: callResult,
		}
	case DebuggerCommandLoadProgram:
		callResult := c.debugger.LoadProgram(cmd.LoadProgramArgs)
		result = &DebuggerCommandResult{
			Id:                cmd.Id,
			Command:           cmd.Command,
			LoadProgramResult: callResult,
		}
	case DebuggerCommandLoadSystemFromFile:
		callResult := c.debugger.LoadSystemFromFile(cmd.LoadSystemFromFileArgs)
		result = &DebuggerCommandResult{
			Id:                       cmd.Id,
			Command:                  cmd.Command,
			LoadSystemFromFileResult: callResult,
		}
	case DebuggerCommandLoadSystemFromEmbedded:
		callResult := c.debugger.LoadSystemFromEmbedded()
		result = &DebuggerCommandResult{
			Id:                           cmd.Id,
			Command:                      cmd.Command,
			LoadSystemFromEmbeddedResult: callResult,
		}
	case DebuggerCommandLoadProgramFromFile:
		callResult := c.debugger.LoadProgramFromFile(cmd.LoadProgramFromFileArgs)
		result = &DebuggerCommandResult{
			Id:                        cmd.Id,
			Command:                   cmd.Command,
			LoadProgramFromFileResult: callResult,
		}
	case DebuggerCommandLoadRuntime:
		callResult := c.debugger.LoadRuntime(cmd.LoadRuntimeArgs)
		result = &DebuggerCommandResult{
			Id:                cmd.Id,
			Command:           cmd.Command,
			LoadRuntimeResult: callResult,
		}
	case DebuggerCommandLoad:
		callResult := c.debugger.Load(cmd.LoadArgs)
		result = &DebuggerCommandResult{
			Id:         cmd.Id,
			Command:    cmd.Command,
			LoadResult: callResult,
		}
	default:
		err = fmt.Errorf("unknown command ID: %d", cmd.Command)
	}

	return
}

// Code generated by codegen; DO NOT EDIT.

// DebuggerCommandId is an enum of all supported debugger commands
type DebuggerCommandId int

const (
	// Step executes a single instruction step. Returns execution state after the step completes.
	// Args specify step mode and optional step count. See [StepArgs] and [ExecutionResult].
	DebuggerCommandStep DebuggerCommandId = DebuggerCommandId(0)
	// Continue resumes execution until the next breakpoint, watchpoint, or program termination.
	// Returns execution state when execution stops. See [ExecutionResult].
	DebuggerCommandContinue DebuggerCommandId = DebuggerCommandId(1)
	// Run starts program execution from the beginning. Equivalent to Reset followed by Continue.
	// Returns execution state when execution stops. See [ExecutionResult].
	DebuggerCommandRun DebuggerCommandId = DebuggerCommandId(2)
	// Interrupt stops the currently running program and returns control to the debugger.
	// Returns execution state after interruption. See [ExecutionResult].
	DebuggerCommandInterrupt DebuggerCommandId = DebuggerCommandId(3)
	// Break adds a code breakpoint. Args specify the breakpoint location by source or address.
	// See [BreakArgs] and [BreakResult] for details.
	DebuggerCommandBreak DebuggerCommandId = DebuggerCommandId(4)
	// Watch adds a memory/data watchpoint. Args specify the memory location and access type.
	// See [WatchArgs] and [WatchResult] for details.
	DebuggerCommandWatch DebuggerCommandId = DebuggerCommandId(5)
	// RemoveBreakpoint removes a code breakpoint by ID. See [RemoveBreakpointArgs] and [RemoveBreakpointResult].
	DebuggerCommandRemoveBreakpoint DebuggerCommandId = DebuggerCommandId(6)
	// RemoveWatchpoint removes a memory watchpoint by ID. See [RemoveWatchpointArgs] and [RemoveWatchpointResult].
	DebuggerCommandRemoveWatchpoint DebuggerCommandId = DebuggerCommandId(7)
	// List returns all active code breakpoints and memory watchpoints. See [ListResult].
	DebuggerCommandList DebuggerCommandId = DebuggerCommandId(8)
	// Disasm disassembles instructions from a specified address. Args specify the address and optional count.
	// See [DisasmArgs] and [DisasmResult] for details.
	DebuggerCommandDisasm DebuggerCommandId = DebuggerCommandId(9)
	// CurrentInstruction returns the instruction at the current program counter. See [CurrentInstructionResult].
	DebuggerCommandCurrentInstruction DebuggerCommandId = DebuggerCommandId(10)
	// Memory displays memory contents at a specified address. Args specify the address and optional byte count.
	// See [MemoryArgs] and [MemoryResult] for details.
	DebuggerCommandMemory DebuggerCommandId = DebuggerCommandId(11)
	// Source displays source code around a specified location. Args specify the location and context display mode.
	// See [SourceArgs] and [SourceResult] for details.
	DebuggerCommandSource DebuggerCommandId = DebuggerCommandId(12)
	// CurrentSource displays source code around the current execution location. Args specify context display options.
	// See [CurrentSourceArgs] and [SourceResult] for details.
	DebuggerCommandCurrentSource DebuggerCommandId = DebuggerCommandId(13)
	// Eval evaluates an expression in the current CPU context. Args specify the expression to evaluate.
	// See [EvalArgs] and [EvalResult] for details.
	DebuggerCommandEval DebuggerCommandId = DebuggerCommandId(14)
	// Info returns debugger state, system configuration, program info, or runtime info based on args.
	// See [InfoArgs] and [InfoResult] for details.
	DebuggerCommandInfo DebuggerCommandId = DebuggerCommandId(15)
	// Registers returns all CPU register values and status flags. See [RegistersResult].
	DebuggerCommandRegisters DebuggerCommandId = DebuggerCommandId(16)
	// Stack returns the call stack and stack memory contents. See [StackResult].
	DebuggerCommandStack DebuggerCommandId = DebuggerCommandId(17)
	// Vars returns the values of accessible local variables and parameters. See [VarsResult].
	DebuggerCommandVars DebuggerCommandId = DebuggerCommandId(18)
	// Symbols returns function, global, and label symbols matching optional filter criteria.
	// See [SymbolsArgs] and [SymbolsResult] for details.
	DebuggerCommandSymbols DebuggerCommandId = DebuggerCommandId(19)
	// Reset resets the debugged program to its initial state. Returns execution state. See [ExecutionResult].
	DebuggerCommandReset DebuggerCommandId = DebuggerCommandId(20)
	// Restart resets and continues program execution (equivalent to Reset followed by Continue). See [ExecutionResult].
	DebuggerCommandRestart DebuggerCommandId = DebuggerCommandId(21)
	// LoadSystem loads the embedded default system configuration. See [LoadSystemArgs] and [LoadSystemFromEmbeddedResult].
	DebuggerCommandLoadSystem DebuggerCommandId = DebuggerCommandId(22)
	// LoadProgram loads a program from a file, optionally compiling it if needed.
	// See [LoadProgramArgs] and [LoadProgramFromFileResult] for details.
	DebuggerCommandLoadProgram DebuggerCommandId = DebuggerCommandId(23)
	// LoadSystemFromFile loads system configuration from a YAML file.
	// See [LoadSystemFromFileArgs] and [LoadSystemFromFileResult] for details.
	DebuggerCommandLoadSystemFromFile DebuggerCommandId = DebuggerCommandId(24)
	// LoadSystemFromEmbedded loads the embedded default system configuration.
	// Returns the loaded system information. See [LoadSystemFromEmbeddedResult].
	DebuggerCommandLoadSystemFromEmbedded DebuggerCommandId = DebuggerCommandId(25)
	// LoadProgramFromFile loads a program from a file, optionally compiling it if needed.
	// This is the full-named version of LoadProgram().
	// See [LoadProgramFromFileArgs] and [LoadProgramFromFileResult] for details.
	DebuggerCommandLoadProgramFromFile DebuggerCommandId = DebuggerCommandId(26)
	// LoadRuntime configures the execution runtime (interpreter engine) used to run the debugged program.
	// See [LoadRuntimeArgs] and [LoadRuntimeResult] for details.
	DebuggerCommandLoadRuntime DebuggerCommandId = DebuggerCommandId(27)
	// Load loads program, system, and runtime configuration from a single YAML descriptor file or individual components.
	// See [LoadArgs] and [LoadResult] for details.
	DebuggerCommandLoad DebuggerCommandId = DebuggerCommandId(28)
)

func (e DebuggerCommandId) String() string {

	switch e {
	case DebuggerCommandStep:
		return "DebuggerCommandStep"
	case DebuggerCommandContinue:
		return "DebuggerCommandContinue"
	case DebuggerCommandRun:
		return "DebuggerCommandRun"
	case DebuggerCommandInterrupt:
		return "DebuggerCommandInterrupt"
	case DebuggerCommandBreak:
		return "DebuggerCommandBreak"
	case DebuggerCommandWatch:
		return "DebuggerCommandWatch"
	case DebuggerCommandRemoveBreakpoint:
		return "DebuggerCommandRemoveBreakpoint"
	case DebuggerCommandRemoveWatchpoint:
		return "DebuggerCommandRemoveWatchpoint"
	case DebuggerCommandList:
		return "DebuggerCommandList"
	case DebuggerCommandDisasm:
		return "DebuggerCommandDisasm"
	case DebuggerCommandCurrentInstruction:
		return "DebuggerCommandCurrentInstruction"
	case DebuggerCommandMemory:
		return "DebuggerCommandMemory"
	case DebuggerCommandSource:
		return "DebuggerCommandSource"
	case DebuggerCommandCurrentSource:
		return "DebuggerCommandCurrentSource"
	case DebuggerCommandEval:
		return "DebuggerCommandEval"
	case DebuggerCommandInfo:
		return "DebuggerCommandInfo"
	case DebuggerCommandRegisters:
		return "DebuggerCommandRegisters"
	case DebuggerCommandStack:
		return "DebuggerCommandStack"
	case DebuggerCommandVars:
		return "DebuggerCommandVars"
	case DebuggerCommandSymbols:
		return "DebuggerCommandSymbols"
	case DebuggerCommandReset:
		return "DebuggerCommandReset"
	case DebuggerCommandRestart:
		return "DebuggerCommandRestart"
	case DebuggerCommandLoadSystem:
		return "DebuggerCommandLoadSystem"
	case DebuggerCommandLoadProgram:
		return "DebuggerCommandLoadProgram"
	case DebuggerCommandLoadSystemFromFile:
		return "DebuggerCommandLoadSystemFromFile"
	case DebuggerCommandLoadSystemFromEmbedded:
		return "DebuggerCommandLoadSystemFromEmbedded"
	case DebuggerCommandLoadProgramFromFile:
		return "DebuggerCommandLoadProgramFromFile"
	case DebuggerCommandLoadRuntime:
		return "DebuggerCommandLoadRuntime"
	case DebuggerCommandLoad:
		return "DebuggerCommandLoad"
	default:
		return "unknown"
	}
}
func DebuggerCommandIdFromString(s string) (DebuggerCommandId, error) {

	switch s {
	case "DebuggerCommandStep":
		return DebuggerCommandStep, nil
	case "DebuggerCommandContinue":
		return DebuggerCommandContinue, nil
	case "DebuggerCommandRun":
		return DebuggerCommandRun, nil
	case "DebuggerCommandInterrupt":
		return DebuggerCommandInterrupt, nil
	case "DebuggerCommandBreak":
		return DebuggerCommandBreak, nil
	case "DebuggerCommandWatch":
		return DebuggerCommandWatch, nil
	case "DebuggerCommandRemoveBreakpoint":
		return DebuggerCommandRemoveBreakpoint, nil
	case "DebuggerCommandRemoveWatchpoint":
		return DebuggerCommandRemoveWatchpoint, nil
	case "DebuggerCommandList":
		return DebuggerCommandList, nil
	case "DebuggerCommandDisasm":
		return DebuggerCommandDisasm, nil
	case "DebuggerCommandCurrentInstruction":
		return DebuggerCommandCurrentInstruction, nil
	case "DebuggerCommandMemory":
		return DebuggerCommandMemory, nil
	case "DebuggerCommandSource":
		return DebuggerCommandSource, nil
	case "DebuggerCommandCurrentSource":
		return DebuggerCommandCurrentSource, nil
	case "DebuggerCommandEval":
		return DebuggerCommandEval, nil
	case "DebuggerCommandInfo":
		return DebuggerCommandInfo, nil
	case "DebuggerCommandRegisters":
		return DebuggerCommandRegisters, nil
	case "DebuggerCommandStack":
		return DebuggerCommandStack, nil
	case "DebuggerCommandVars":
		return DebuggerCommandVars, nil
	case "DebuggerCommandSymbols":
		return DebuggerCommandSymbols, nil
	case "DebuggerCommandReset":
		return DebuggerCommandReset, nil
	case "DebuggerCommandRestart":
		return DebuggerCommandRestart, nil
	case "DebuggerCommandLoadSystem":
		return DebuggerCommandLoadSystem, nil
	case "DebuggerCommandLoadProgram":
		return DebuggerCommandLoadProgram, nil
	case "DebuggerCommandLoadSystemFromFile":
		return DebuggerCommandLoadSystemFromFile, nil
	case "DebuggerCommandLoadSystemFromEmbedded":
		return DebuggerCommandLoadSystemFromEmbedded, nil
	case "DebuggerCommandLoadProgramFromFile":
		return DebuggerCommandLoadProgramFromFile, nil
	case "DebuggerCommandLoadRuntime":
		return DebuggerCommandLoadRuntime, nil
	case "DebuggerCommandLoad":
		return DebuggerCommandLoad, nil
	default:
		return 0, fmt.Errorf("unknown %s: %s", "DebuggerCommandId", s)
	}
}
func (e DebuggerCommandId) MarshalJSON() ([]byte, error) {

	return json.Marshal(e.String())
}
func (e *DebuggerCommandId) UnmarshalJSON(data []byte) error {

	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return err
	}
	val, err := DebuggerCommandIdFromString(str)
	if err != nil {
		return err
	}
	*e = val

	return nil
}

// A map of all DebuggerCommandId values for easy lookup
var DebuggerCommandIdValues map[DebuggerCommandId]bool = map[DebuggerCommandId]bool{
	DebuggerCommandStep:                   true,
	DebuggerCommandContinue:               true,
	DebuggerCommandRun:                    true,
	DebuggerCommandInterrupt:              true,
	DebuggerCommandBreak:                  true,
	DebuggerCommandWatch:                  true,
	DebuggerCommandRemoveBreakpoint:       true,
	DebuggerCommandRemoveWatchpoint:       true,
	DebuggerCommandList:                   true,
	DebuggerCommandDisasm:                 true,
	DebuggerCommandCurrentInstruction:     true,
	DebuggerCommandMemory:                 true,
	DebuggerCommandSource:                 true,
	DebuggerCommandCurrentSource:          true,
	DebuggerCommandEval:                   true,
	DebuggerCommandInfo:                   true,
	DebuggerCommandRegisters:              true,
	DebuggerCommandStack:                  true,
	DebuggerCommandVars:                   true,
	DebuggerCommandSymbols:                true,
	DebuggerCommandReset:                  true,
	DebuggerCommandRestart:                true,
	DebuggerCommandLoadSystem:             true,
	DebuggerCommandLoadProgram:            true,
	DebuggerCommandLoadSystemFromFile:     true,
	DebuggerCommandLoadSystemFromEmbedded: true,
	DebuggerCommandLoadProgramFromFile:    true,
	DebuggerCommandLoadRuntime:            true,
	DebuggerCommandLoad:                   true,
}
