// Code generated by "stringer -type=GlobalType"; DO NOT EDIT.

package llvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GlobalUnknown-0]
	_ = x[GlobalFunction-1]
	_ = x[GlobalObject-2]
}

const _GlobalType_name = "GlobalUnknownGlobalFunctionGlobalObject"

var _GlobalType_index = [...]uint8{0, 13, 27, 39}

func (i GlobalType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GlobalType_index)-1 {
		return "GlobalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GlobalType_name[_GlobalType_index[idx]:_GlobalType_index[idx+1]]
}
